Repository GeotrekCE/Geotrek-admin, pull requests merged in 2023-09, with the labels that each got.

#3657 Update CSS of Altimetry
  docs/changelog.rst
  geotrek/altimetry/static/altimetry/style.css
Labels: 💫 Improvements

#3678 Update architecture schema for design section
  docs/changelog.rst
  docs/contribute/design.rst
  docs/images/architecture-1.0.jpg
  docs/images/architecture-1.0.png
Labels: 📝 Documentation

#3677 ⬆ Upgrade mapentity to 8.5.6
  requirements.txt
Labels: dependencies

#3680 Replace dead link for itinerant trek exemple
  docs/changelog.rst
  docs/usage/treks.rst
Labels: 📝 Documentation

#3682 Update documentation for releases
  docs/CONTRIBUTING.rst
Labels: 📝 Documentation

#3684 MNT values must be integer, help on how to transform those values (#1891)
  docs/changelog.rst
  docs/install/loading-data.rst
Labels: 📝 Documentation

#3683 Remove review field from ServiceType model (#1669)
  docs/changelog.rst
  geotrek/trekking/fixtures/basic.json
  geotrek/trekking/migrations/0047_remove_servicetype_review.py
  geotrek/trekking/models.py
Labels: 💫 Improvements

#3704 Delete unused code
  geotrek/zoning/views.py
Labels: ♻️ Refactoring

#3659 Fix missing geometries for HD Views in APIv2 (refs #3701)
  docs/changelog.rst
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/views/trekking.py
Labels: 🐛 bug

#3708 📝 Update documentation fr translation files (#993)
  docs/changelog.rst
  docs/locales/fr/LC_MESSAGES/CONTRIBUTING.po
  docs/locales/fr/LC_MESSAGES/authors.po
  docs/locales/fr/LC_MESSAGES/changelog.po
  docs/locales/fr/LC_MESSAGES/contribute.po
  docs/locales/fr/LC_MESSAGES/faq.po
  docs/locales/fr/LC_MESSAGES/index.po
  docs/locales/fr/LC_MESSAGES/install.po
  docs/locales/fr/LC_MESSAGES/usage.po
  docs/requirements.txt
Labels: 📝 Documentation

#3713 Uniformize documentation section of the doc
  docs/changelog.rst
  docs/contribute/development.rst
  docs/contribute/documentation.rst
  docs/locales/fr/LC_MESSAGES/changelog.po
Labels: 📝 Documentation

#3715 📝 Move user management section to user manual (#3709)
  docs/changelog.rst
  docs/install/configuration.rst
  docs/locales/fr/LC_MESSAGES/changelog.po
  docs/locales/fr/LC_MESSAGES/install.po
  docs/locales/fr/LC_MESSAGES/usage.po
  docs/usage/configuration-ttw.rst
Labels: 📝 Documentation

#3720 Increase size for label of TouristicEventOrganizer model creating crashs in migrations (#3719)
  docs/changelog.rst
  geotrek/tourism/migrations/0043_auto_20230804_1317.py
  geotrek/tourism/migrations/0048_alter_touristiceventorganizer_label.py
  geotrek/tourism/models.py
Labels: 🐛 bug

#3729 Bump mapentity to 8.6.1
  Dockerfile
  docs/changelog.rst
  geotrek/settings/base.py
  requirements.txt
Labels: dependencies, python

#3722 Reorganize settings section
  docs/changelog.rst
  docs/install/advanced-configuration.rst
  docs/install/configuration.rst
  docs/install/maintenance.rst
  docs/locales/fr/LC_MESSAGES/authors.po
  docs/locales/fr/LC_MESSAGES/changelog.po
  docs/locales/fr/LC_MESSAGES/contribute.po
  docs/locales/fr/LC_MESSAGES/faq.po
  docs/locales/fr/LC_MESSAGES/index.po
  docs/locales/fr/LC_MESSAGES/install.po
Labels: 📝 Documentation

#3744 Refactor accessibility attachments
  docs/changelog.rst
  geotrek/common/forms.py
  geotrek/common/templates/common/attachment_accessibility_list.html
  geotrek/common/tests/test_attachments.py
  geotrek/common/urls.py
  geotrek/urls.py
Labels: ♻️ Refactoring

#3748 :bug: [BUG] Fix missing update rights for Infrastructure Condition and Infrastructure Type with no structure
  docs/changelog.rst
  geotrek/infrastructure/admin.py
Labels: 🐛 bug

#3746 🐛 [Bug fixes] handle case where year is none when loading signage - #3611
  docs/changelog.rst
  geotrek/common/tests/utils.py
  geotrek/signage/management/commands/loadsignage.py
  geotrek/signage/tests/test_command_signage.py
Labels: 🐛 bug

#3758 Add new contributors to authors of the project list
  docs/authors.rst
  docs/changelog.rst
Labels: 📝 Documentation

#3757 Sort API V2 by begin date by default on touristic events (#3597)
  docs/changelog.rst
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/views/tourism.py
Labels: 💫 Improvements

#3767 fix: installed app order env_dev
  geotrek/settings/env_dev.py
Labels: 🚑 Hotfix

#3773 Check running migrations in CI
  .github/workflows/test.yml
Labels: 👷 CI
