Repository GeotrekCE/Geotrek-admin, pull requests merged in 2023-03, with the labels that each got.

#3424 Add arguments loadsignage : sealing / manager (#3377)
  docs/changelog.rst
  geotrek/signage/management/commands/loadsignage.py
  geotrek/signage/tests/data/signage.dbf
  geotrek/signage/tests/test_command_signage.py
Labels: ✨ Feature

#3476 💚 Update coverage 7.1
  dev-requirements.txt
  setup.cfg
Labels: 💚 Fix CI Build

#3350 Update data model
  docs/changelog.rst
  docs/data-model/authent.pdf
  docs/data-model/cirkwi.pdf
  docs/data-model/core.pdf
  docs/data-model/diving.pdf
  docs/data-model/feedback.pdf
  docs/data-model/flatpages.pdf
  docs/data-model/global.pdf
  docs/data-model/infrastructure.pdf
  docs/data-model/land.pdf
  docs/data-model/maintenance.pdf
  docs/data-model/outdoor.pdf
  docs/data-model/sensitivity.pdf
  docs/data-model/signage.pdf
  docs/data-model/tourism.pdf
  docs/data-model/trekking.pdf
  docs/data-model/zoning.pdf
Labels: 📝 Documentation

#3481 Suricate workflow : enable bypass moderation
  docs/changelog.rst
  docs/install/advanced-configuration.rst
  geotrek/common/views.py
  geotrek/feedback/forms.py
  geotrek/feedback/management/commands/sync_suricate.py
  geotrek/feedback/models.py
  geotrek/feedback/parsers.py
  geotrek/feedback/static/feedback/workflow.js
  geotrek/feedback/templates/feedback/report_detail_attributes.html
  geotrek/feedback/templates/feedback/report_form.html
  geotrek/feedback/templatetags/feedback_tags.py
  geotrek/feedback/tests/factories.py
  geotrek/feedback/tests/test_forms.py
  geotrek/feedback/tests/test_models.py
  geotrek/feedback/tests/test_suricate_sync.py
  geotrek/feedback/tests/test_views.py
  geotrek/feedback/views.py
  geotrek/maintenance/forms.py
  geotrek/settings/base.py
Labels: ✨ Feature

#3537 bump DRF dependencies
  requirements.txt
Labels: dependencies, python
