Repository GeotrekCE/Geotrek-admin, pull requests merged in 2023-12, with the labels that each got.

#3826 Add conditions on signage (refs #3847)
  docs/changelog.rst
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/serializers.py
  geotrek/api/v2/urls.py
  geotrek/api/v2/views/__init__.py
  geotrek/api/v2/views/signage.py
  geotrek/infrastructure/forms.py
  geotrek/infrastructure/models.py
  geotrek/maintenance/tests/test_views.py
  geotrek/signage/admin.py
  geotrek/signage/filters.py
  geotrek/signage/forms.py
  geotrek/signage/management/commands/loadsignage.py
  geotrek/signage/migrations/0036_auto_20231013_1326.py
  geotrek/signage/migrations/0037_auto_20231016_1331.py
  geotrek/signage/migrations/0038_auto_20231023_1233.py
  geotrek/signage/models.py
  geotrek/signage/parsers.py
  geotrek/signage/serializers.py
  geotrek/signage/templates/signage/blade_detail.html
  geotrek/signage/templates/signage/signage_detail_attributes.html
  geotrek/signage/templates/signage/sql/post_10_views.sql
  geotrek/signage/tests/data/geotrek_parser_v2/signage.json
  geotrek/signage/tests/data/geotrek_parser_v2/signage_conditions.json
  geotrek/signage/tests/data/signage.dbf
  geotrek/signage/tests/data/signage.qix
  geotrek/signage/tests/data/signage.shp
  geotrek/signage/tests/data/signage.shx
  geotrek/signage/tests/factories.py
  geotrek/signage/tests/test_admin.py
  geotrek/signage/tests/test_command_signage.py
  geotrek/signage/tests/test_models.py
  geotrek/signage/tests/test_parsers.py
  geotrek/signage/tests/test_views.py
  geotrek/signage/views.py
Labels: 💫 Improvements

#3854 Update advanced-configuration.rst
  docs/install/advanced-configuration.rst
Labels: 📝 Documentation

#3863 Add conf to use Makefile.perso.mk
  .gitignore
  Makefile
Labels: 🛠️ Tools

#3862 💫 [IMPR] Allow configuring headers in parsers requests (refs #3861)
  docs/changelog.rst
  geotrek/common/parsers.py
  geotrek/sensitivity/tests/test_parsers.py
  geotrek/tourism/tests/test_parsers.py
Labels: 💫 Improvements

#3865 Sort bladeType alphabetically #3821
  docs/changelog.rst
  geotrek/signage/migrations/0039_alter_bladetype_options.py
  geotrek/signage/models.py
Labels: 💫 Improvements

#3843 ✨ [FEAT] Generalize ``AccessMean`` model and add field ``access`` to ``Intervention`` (refs #3819)
  docs/changelog.rst
  geotrek/common/admin.py
  geotrek/common/migrations/0036_accessmean.py
  geotrek/common/models.py
  geotrek/common/templates/common/sql/post_90_defaults.sql
  geotrek/common/tests/factories.py
  geotrek/infrastructure/admin.py
  geotrek/infrastructure/fixtures/basic.json
  geotrek/infrastructure/migrations/0036_infrastructure_access_tmp.py
  geotrek/infrastructure/migrations/0037_remove_infrastructure_access.py
  geotrek/infrastructure/migrations/0038_rename_access_tmp_infrastructure_access.py
  geotrek/infrastructure/models.py
  geotrek/infrastructure/templates/infrastructure/sql/post_10_views.sql
  geotrek/infrastructure/templates/infrastructure/sql/post_90_defaults.sql
  geotrek/infrastructure/tests/factories.py
  geotrek/maintenance/forms.py
  geotrek/maintenance/migrations/0023_intervention_access.py
  geotrek/maintenance/models.py
  geotrek/maintenance/templates/maintenance/intervention_detail.html
  geotrek/maintenance/templates/maintenance/sql/post_20_views.sql
  geotrek/maintenance/tests/test_views.py
  geotrek/signage/migrations/0040_signage_access_tmp.py
  geotrek/signage/migrations/0041_remove_signage_access.py
  geotrek/signage/migrations/0042_rename_access_tmp_signage_access.py
  geotrek/signage/templates/signage/sql/post_10_views.sql
Labels: ✨ Feature
