Repository GeotrekCE/Geotrek-admin, pull requests merged in 2023-02, with the labels that each got.

#3348 feat: add missing attachements on SensitivityArea APIs
  docs/changelog.rst
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/serializers.py
  geotrek/api/v2/views/sensitivity.py
  geotrek/sensitivity/mixins.py
  geotrek/sensitivity/serializers.py
  geotrek/sensitivity/tests/test_functional.py
  geotrek/sensitivity/tests/test_views.py
  geotrek/sensitivity/views.py
Labels: improvments

#3465 :bug: Fix APIv2 filters performances were deteriorated
  docs/changelog.rst
  geotrek/api/v2/filters.py
  geotrek/api/v2/views/common.py
Labels: bug

#3478 Fix sensitivity layer was always loaded before click
  docs/changelog.rst
  geotrek/sensitivity/static/sensitivity/main.js
Labels: 💫 Improvements

#3477 :memo: Document HD Views usage
  docs/images/user-manual/hd_view_annotations.png
  docs/images/user-manual/hd_view_detail.png
  docs/images/user-manual/hd_view_trek.png
  docs/usage/outdoor.rst
Labels: 📝 Documentation

#3475 🐛 Fix failing test on some environments
  geotrek/api/tests/test_v2.py
Labels: ✅ Tests

#3386 [SENSITIVITY] Adding rules to sensitive areas
  docs/changelog.rst
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/serializers.py
  geotrek/api/v2/views/sensitivity.py
  geotrek/sensitivity/admin.py
  geotrek/sensitivity/forms.py
  geotrek/sensitivity/locale/de/LC_MESSAGES/django.po
  geotrek/sensitivity/locale/en/LC_MESSAGES/django.po
  geotrek/sensitivity/locale/es/LC_MESSAGES/django.po
  geotrek/sensitivity/locale/fr/LC_MESSAGES/django.po
  geotrek/sensitivity/locale/it/LC_MESSAGES/django.po
  geotrek/sensitivity/locale/nl/LC_MESSAGES/django.po
  geotrek/sensitivity/migrations/0027_auto_20230202_2202.py
  geotrek/sensitivity/models.py
  geotrek/sensitivity/serializers.py
  geotrek/sensitivity/templates/sensitivity/sensitivearea_detail_attributes.html
  geotrek/sensitivity/tests/factories.py
  geotrek/sensitivity/tests/test_functional.py
  geotrek/sensitivity/tests/test_parsers.py
  geotrek/sensitivity/tests/test_views.py
  geotrek/sensitivity/translation.py
Labels: ✨ Feature

#3395 :lock: Sanitize Paperclip attachments
  docs/changelog.rst
  docs/install/advanced-configuration.rst
  docs/install/installation.rst
  geotrek/common/forms.py
  geotrek/common/migrations/0030_auto_20230202_1535.py
  geotrek/common/models.py
  geotrek/common/parsers.py
  geotrek/common/templates/common/sql/post_90_defaults.sql
  geotrek/common/tests/data/organism6.xls
  geotrek/common/tests/data/organism7.xls
  geotrek/common/tests/test_admin.py
  geotrek/common/tests/test_attachments.py
  geotrek/common/tests/test_parsers.py
  geotrek/common/tests/test_sql.py
  geotrek/common/utils/testdata.py
  geotrek/feedback/parsers.py
  geotrek/feedback/tests/test_suricate_sync.py
  geotrek/feedback/tests/test_views.py
  geotrek/feedback/views.py
  geotrek/settings/base.py
  geotrek/tourism/tests/test_views.py
  requirements.txt
Labels: Security

#3497 :dizzy: Allow zoom on HD Views depending on tile depth
  docs/changelog.rst
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/serializers.py
  geotrek/common/models.py
  geotrek/common/static/common/js/hdviewpoint_viewer.js
Labels: 💫 Improvements
