Repository GeotrekCE/Geotrek-admin, pull requests merged in 2023-11, with the labels that each got.

#3816 🐛 [BUG] Fix missing geometries for HD Views in APIv2 (refs #3701)
  docs/changelog.rst
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/views/outdoor.py
  geotrek/api/v2/views/trekking.py
Labels: 🐛 bug

#3817 🐛 [BUG] Fix cannot click on objects after customizing map styles (refs #3800)
  docs/changelog.rst
  geotrek/feedback/static/feedback/main.js
  geotrek/infrastructure/static/infrastructure/main.js
  geotrek/outdoor/static/outdoor/main.js
  geotrek/sensitivity/static/sensitivity/main.js
  geotrek/signage/static/signage/main.js
  geotrek/tourism/static/tourism/main.js
Labels: 🐛 bug

#3831 Fix typo in PR template
  .github/pull_request_template.md
Labels: 📝 Documentation

#3834 fix PNG elevation profile with cairosvg (#3833)
  docs/changelog.rst
  geotrek/altimetry/models.py
  geotrek/altimetry/views.py
  geotrek/api/management/commands/sync_mobile.py
  geotrek/core/views.py
  geotrek/trekking/models.py
  geotrek/trekking/tests/test_views.py
  geotrek/trekking/views.py
Labels: 🐛 bug

#3827 📝 [DOC] Improve database migration doc
  docs/changelog.rst
  docs/install/maintenance.rst
Labels: 📝 Documentation

#3838 📝 [DOC] Fix database migration doc
  docs/changelog.rst
  docs/install/maintenance.rst
Labels: 📝 Documentation

#3832 Improve help and doc for the `loadinfrastructure` command
  docs/changelog.rst
  docs/install/import.rst
  geotrek/infrastructure/management/commands/loadinfrastructure.py
Labels: 📝 Documentation

#3721 Add fixture rules of sensitive area #3470
  docs/changelog.rst
  docs/install/advanced-configuration.rst
  geotrek/sensitivity/fixtures/rules.json
  geotrek/sensitivity/fixtures/upload/rules/ANCHOR-FORBIDDEN_054.svg
  geotrek/sensitivity/fixtures/upload/rules/BIKES-FORBIDDEN_053.svg
  geotrek/sensitivity/fixtures/upload/rules/BIVOUAC-FORBIDDEN_042.svg
  geotrek/sensitivity/fixtures/upload/rules/BIVOUAC-REGULATED_153.svg
  geotrek/sensitivity/fixtures/upload/rules/CAMPING-FORBIDDEN_041.svg
  geotrek/sensitivity/fixtures/upload/rules/CAMPINGCAR-FORBIDDEN_043.svg
  geotrek/sensitivity/fixtures/upload/rules/CAMPINGCARS-FORBIDDEN_043.svg
  geotrek/sensitivity/fixtures/upload/rules/CANYON-FORBIDDEN_900.svg
  geotrek/sensitivity/fixtures/upload/rules/CANYON-REGULATED_902.svg
  geotrek/sensitivity/fixtures/upload/rules/CAR-FORBIDDEN_051.svg
  geotrek/sensitivity/fixtures/upload/rules/CARAVAN-FORBIDDEN_044.svg
  geotrek/sensitivity/fixtures/upload/rules/CARAVANS-FORBIDDEN_044.svg
  geotrek/sensitivity/fixtures/upload/rules/CARS-FORBIDDEN_051.svg
  geotrek/sensitivity/fixtures/upload/rules/CHASE-FORBIDDEN_022.svg
  geotrek/sensitivity/fixtures/upload/rules/DOG-LEASH_111.svg
  geotrek/sensitivity/fixtures/upload/rules/DOGS-FORBIDDEN_011.svg
  geotrek/sensitivity/fixtures/upload/rules/DOGS-LEASH_111.svg
  geotrek/sensitivity/fixtures/upload/rules/DRONE-FORBIDDEN_074.svg
  geotrek/sensitivity/fixtures/upload/rules/FEEDINGWILDLIFE-FORBIDDEN_036.svg
  geotrek/sensitivity/fixtures/upload/rules/FIRE-FORBIDDEN_033.svg
  geotrek/sensitivity/fixtures/upload/rules/FISHING-FORBIDDEN_023.svg
  geotrek/sensitivity/fixtures/upload/rules/FISHING-TRAP-FORBIDDEN_062.svg
  geotrek/sensitivity/fixtures/upload/rules/HANGGLIDER-FORBIDDEN_056.svg
  geotrek/sensitivity/fixtures/upload/rules/HORSE-FORBIDDEN_055.svg
  geotrek/sensitivity/fixtures/upload/rules/MOTO-FORBIDDEN_052.svg
  geotrek/sensitivity/fixtures/upload/rules/MOTOS-FORBIDDEN_052.svg
  geotrek/sensitivity/fixtures/upload/rules/NOISE-FORBIDDEN_012.svg
  geotrek/sensitivity/fixtures/upload/rules/OUTOFTRAIL-FORBIDDEN_058.svg
  geotrek/sensitivity/fixtures/upload/rules/PARAGLIDING-FORBIDDEN_057.svg
  geotrek/sensitivity/fixtures/upload/rules/PARKING-FORBIDDEN_910.svg
  geotrek/sensitivity/fixtures/upload/rules/PEDESTRIAN-FORBIDDEN_920.svg
  geotrek/sensitivity/fixtures/upload/rules/PEDESTRIAN-REGULATED_922.svg
  geotrek/sensitivity/fixtures/upload/rules/PICKING-FAUNA-FORBIDDEN_061.svg
  geotrek/sensitivity/fixtures/upload/rules/PICKING-FORBIDDEN_021.svg
  geotrek/sensitivity/fixtures/upload/rules/PICKING-FUNGI-FORBIDDEN_070.svg
  geotrek/sensitivity/fixtures/upload/rules/PICKING-MINERALS-FORBIDDEN_060.svg
  geotrek/sensitivity/fixtures/upload/rules/SMOKING-FORBIDDEN_034.svg
  geotrek/sensitivity/fixtures/upload/rules/SWIMMING-FORBIDDEN_068.svg
  geotrek/sensitivity/fixtures/upload/rules/WASHINGCAR-FORBIDDEN_059.svg
  geotrek/sensitivity/fixtures/upload/rules/WASTE-FORBIDDEN_031.svg
  geotrek/sensitivity/templates/sensitivity/sql/post_90_defaults.sql
Labels: 💫 Improvements

#3723 🐛[BUG] v_outdoor extract all geometry type - #3603
  docs/changelog.rst
  geotrek/outdoor/templates/outdoor/sql/post_20_views.sql
Labels: 🐛 bug
