Repository GeotrekCE/Geotrek-admin, pull requests merged in 2023-01, with the labels that each got.

#3405 🐛 Use X-Forwarded-Proto header to define API v2 cache key
  docs/changelog.rst
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/viewsets.py
Labels: bug

#3406 :bug: Check pictogram exist on categories during generation of pdfs
  docs/changelog.rst
  geotrek/diving/templates/diving/dive_public_pdf_base.html
  geotrek/outdoor/templates/outdoor/course_public_pdf_base.html
  geotrek/outdoor/templates/outdoor/site_public_pdf_base.html
  geotrek/trekking/templates/trekking/trek_public_pdf_base.html
  geotrek/trekking/tests/test_views.py
Labels: bug

#3408 :bug: Fix apidae parser should not update every time
  docs/changelog.rst
  geotrek/common/parsers.py
  geotrek/trekking/parsers.py
  geotrek/trekking/tests/data/apidae_trek_parser/trek_no_plan_error.json
  geotrek/trekking/tests/test_parsers.py
Labels: bug

#3418 :bug: Fix parser translation field, add modified when new value is different from old value (for each language)
  docs/changelog.rst
  geotrek/common/parsers.py
  geotrek/trekking/tests/test_parsers.py
Labels: bug

#3413 :bug: Change for absolute url on trek's description in api v2
  docs/changelog.rst
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/serializers.py
Labels: bug

#3417 :sparkles: Add blade type on signage detail view
  docs/changelog.rst
  geotrek/signage/templates/signage/signage_detail_attributes.html
Labels: improvments

#3426 🐛 Fix intervention datatable list when no target defined
  docs/changelog.rst
  geotrek/maintenance/filters.py
  geotrek/maintenance/models.py
  geotrek/maintenance/templates/maintenance/sql/post_10_interventions.sql
  geotrek/maintenance/templates/maintenance/sql/pre_10_cleanup.sql
  geotrek/maintenance/tests/test_filters.py
  geotrek/maintenance/tests/test_models.py
Labels: bug

#3438 build(deps): bump requests from 2.18.1 to 2.18.2
  requirements.txt
Labels: dependencies, python

#3441 build(deps): bump psycopg2 from 2.9.3 to 2.9.5
  requirements.txt
  setup.py
Labels: dependencies, python

#3442 build(deps): bump sentry-sdk from 1.5.9 to 1.14.0
  requirements.txt
Labels: dependencies, python

#3429 Improve APIDAE Trek parser output with entities external IDs
  docs/changelog.rst
  geotrek/trekking/locale/de/LC_MESSAGES/django.po
  geotrek/trekking/locale/en/LC_MESSAGES/django.po
  geotrek/trekking/locale/es/LC_MESSAGES/django.po
  geotrek/trekking/locale/fr/LC_MESSAGES/django.po
  geotrek/trekking/locale/it/LC_MESSAGES/django.po
  geotrek/trekking/locale/nl/LC_MESSAGES/django.po
  geotrek/trekking/parsers.py
Labels: improvments

#3428 Fix: APIDAE Trek parser now raises an error on not continuous segments
  docs/changelog.rst
  geotrek/trekking/locale/de/LC_MESSAGES/django.po
  geotrek/trekking/locale/en/LC_MESSAGES/django.po
  geotrek/trekking/locale/es/LC_MESSAGES/django.po
  geotrek/trekking/locale/fr/LC_MESSAGES/django.po
  geotrek/trekking/locale/it/LC_MESSAGES/django.po
  geotrek/trekking/locale/nl/LC_MESSAGES/django.po
  geotrek/trekking/parsers.py
  geotrek/trekking/tests/data/apidae_trek_parser/trace_with_not_continuous_segments.gpx
  geotrek/trekking/tests/test_parsers.py
Labels: bug
