Repository GeotrekCE/Geotrek-admin, pull requests merged in 2023-10, with the labels that each got.

#3774 fix: Filters on Intervention exports (resolve #3749)
  docs/changelog.rst
  geotrek/maintenance/tests/test_views.py
  geotrek/maintenance/views.py
Labels: 🐛 bug

#3781 fix: cities display on string (refs #3585)
  docs/changelog.rst
  geotrek/infrastructure/models.py
  geotrek/infrastructure/tests/test_models.py
  geotrek/infrastructure/tests/test_views.py
Labels: 🐛 bug

#3782 Update html open source editor
  docs/changelog.rst
  docs/usage/configuration-ttw.rst
Labels: 📝 Documentation

#3784 Bump easy-thumbnails from 2.7 to 2.8.5
  geotrek/api/v2/serializers.py
  requirements.txt
Labels: dependencies, python

#3786 Fix POI cirkwi XML endpoint (#3783)
  docs/changelog.rst
Labels: 🐛 bug

#3794 Fix Aggregator fails when updating Tour steps order (refs #3793)
  docs/changelog.rst
  geotrek/trekking/parsers.py
Labels: 🐛 bug

#3797 [HOTFIX] 🚑 Fix services list display error (refs #3795)
  docs/changelog.rst
  geotrek/trekking/models.py
Labels: 🚑 Hotfix

#3804 Fix `sync_rando` failure with SVG attachment (#3803)
  docs/changelog.rst
  geotrek/common/mixins/models.py
Labels: 🐛 bug

#3810 Hot fix provider choices in list filter forms
  geotrek/core/tests/test_views.py
  geotrek/infrastructure/tests/test_views.py
  geotrek/outdoor/tests/test_views.py
  geotrek/sensitivity/tests/test_views.py
  geotrek/signage/managers.py
  geotrek/tourism/tests/test_views.py
  geotrek/trekking/tests/test_views.py
Labels: 🐛 bug, 🚑 Hotfix

#3811 Fix and improve filter choices (#3812)
  docs/changelog.rst
  geotrek/infrastructure/filters.py
  geotrek/maintenance/filters.py
  geotrek/maintenance/managers.py
  geotrek/signage/filters.py
  geotrek/tourism/filters.py
  geotrek/tourism/tests/test_filters.py
Labels: 🐛 bug

#3813 Refactor filters
  geotrek/cirkwi/filters.py
  geotrek/common/fields.py
  geotrek/common/filters/__init__.py
  geotrek/common/filters/fields.py
  geotrek/common/mixins/filters.py
  geotrek/core/filters.py
  geotrek/core/tests/test_views.py
  geotrek/infrastructure/filters.py
  geotrek/maintenance/filters.py
  geotrek/outdoor/filters.py
  geotrek/sensitivity/filters.py
  geotrek/signage/filters.py
  geotrek/tourism/filters.py
  geotrek/tourism/tests/test_functional.py
  geotrek/trekking/filters.py
  geotrek/trekking/tests/test_views.py
Labels: ♻️ Refactoring
