Repository GeotrekCE/Geotrek-admin, pull requests merged in 2024-04, with the labels that each got.

#4025 📝 Fix PR template URL
  .github/pull_request_template.md
Labels: 📝 Documentation

#4026 📝 Document Max characters by field
  docs/changelog.rst
  docs/install/advanced-configuration.rst
Labels: 📝 Documentation

#4017 Add menus for flat pages
  docs/changelog.rst
  docs/usage/static-pages.rst
  geotrek/api/locale/de/LC_MESSAGES/django.po
  geotrek/api/locale/en/LC_MESSAGES/django.po
  geotrek/api/locale/es/LC_MESSAGES/django.po
  geotrek/api/locale/fr/LC_MESSAGES/django.po
  geotrek/api/locale/it/LC_MESSAGES/django.po
  geotrek/api/locale/nl/LC_MESSAGES/django.po
  geotrek/api/management/commands/sync_mobile.py
  geotrek/api/mobile/serializers/common.py
  geotrek/api/mobile/views/common.py
  geotrek/api/tests/test_mobile/test_api_mobile_flatpage.py
  geotrek/api/tests/test_mobile/test_sync_mobile.py
  geotrek/api/tests/test_utils.py
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/filters.py
  geotrek/api/v2/serializers.py
  geotrek/api/v2/urls.py
  geotrek/api/v2/utils.py
  geotrek/api/v2/views/__init__.py
  geotrek/api/v2/views/flatpages.py
  geotrek/flatpages/admin.py
  geotrek/flatpages/forms.py
  geotrek/flatpages/locale/de/LC_MESSAGES/django.po
  geotrek/flatpages/locale/en/LC_MESSAGES/django.po
  geotrek/flatpages/locale/es/LC_MESSAGES/django.po
  geotrek/flatpages/locale/fr/LC_MESSAGES/django.po
  geotrek/flatpages/locale/it/LC_MESSAGES/django.po
  geotrek/flatpages/locale/nl/LC_MESSAGES/django.po
  geotrek/flatpages/migrations/0010_create_model_MenuItem.py
  geotrek/flatpages/migrations/0011_migrate_flatpage_data.py
  geotrek/flatpages/migrations/0012_change_flatpage_schema.py
  geotrek/flatpages/migrations/0013_fix_page_portals_verbose.py
  geotrek/flatpages/models.py
  geotrek/flatpages/static/flatpages/css/jquery.gridmanager.css
  geotrek/flatpages/static/flatpages/js/jquery.gridmanager.js
  geotrek/flatpages/static/flatpages/js/jquery.gridmanager.min.js
  geotrek/flatpages/static/flatpages/js/menu_item_fieldsets.js
  geotrek/flatpages/templates/flatpages/flatpage_form.html
  geotrek/flatpages/templates/flatpages/sql/post_90_defaults.sql
  geotrek/flatpages/tests/factories.py
  geotrek/flatpages/tests/test_admin.py
  geotrek/flatpages/tests/test_forms.py
  geotrek/flatpages/tests/test_media.py
  geotrek/flatpages/tests/test_models.py
  geotrek/flatpages/translation.py
  geotrek/flatpages/views.py
  geotrek/settings/base.py
  requirements.txt
  setup.cfg
  setup.py
Labels: ✨ Feature

#4020 Add styling and embedding tools for FlatPages content (refs #3921, #3922, #4019)
  docs/changelog.rst
  docs/usage/static-pages.rst
  geotrek/flatpages/forms.py
  geotrek/flatpages/static/flatpages/tinymce/css/flatpage_custom_formats.css
  geotrek/flatpages/static/flatpages/tinymce/js/additional_tinymce_plugins.js
  geotrek/flatpages/static/tiny_mce/plugins/youtube/README.md
  geotrek/flatpages/static/tiny_mce/plugins/youtube/css/styles.css
  geotrek/flatpages/static/tiny_mce/plugins/youtube/img/Google-YouTube-128.png
  geotrek/flatpages/static/tiny_mce/plugins/youtube/img/youtube.gif
  geotrek/flatpages/static/tiny_mce/plugins/youtube/js/main.js
  geotrek/flatpages/static/tiny_mce/plugins/youtube/js/vendor/jquery.js
  geotrek/flatpages/static/tiny_mce/plugins/youtube/langs/de.js
  geotrek/flatpages/static/tiny_mce/plugins/youtube/langs/en.js
  geotrek/flatpages/static/tiny_mce/plugins/youtube/langs/es.js
  geotrek/flatpages/static/tiny_mce/plugins/youtube/langs/fr_FR.js
  geotrek/flatpages/static/tiny_mce/plugins/youtube/langs/hu.js
  geotrek/flatpages/static/tiny_mce/plugins/youtube/langs/it.js
  geotrek/flatpages/static/tiny_mce/plugins/youtube/langs/nl.js
  geotrek/flatpages/static/tiny_mce/plugins/youtube/langs/pl.js
  geotrek/flatpages/static/tiny_mce/plugins/youtube/langs/pt_BR.js
  geotrek/flatpages/static/tiny_mce/plugins/youtube/langs/ru.js
  geotrek/flatpages/static/tiny_mce/plugins/youtube/langs/tr.js
  geotrek/flatpages/static/tiny_mce/plugins/youtube/plugin.js
  geotrek/flatpages/static/tiny_mce/plugins/youtube/plugin.min.js
  geotrek/flatpages/static/tiny_mce/plugins/youtube/view/forms.html
  geotrek/flatpages/static/tiny_mce/plugins/youtube/youtube.html
  geotrek/flatpages/widgets.py
Labels: ✨ Feature

#4024 Add local image upload into flat pages content (ref #3552)
  docs/changelog.rst
  geotrek/flatpages/tests/test_views.py
  geotrek/flatpages/urls.py
  geotrek/flatpages/views.py
  geotrek/flatpages/widgets.py
  geotrek/urls.py
Labels: ✨ Feature

#4033 bump to mapentity 8.7.3
  docs/changelog.rst
  geotrek/common/tests/__init__.py
  geotrek/common/urls.py
  requirements.txt
Labels: dependencies, python

#4030 Fix mobile sync when no picto on themes (fixes #3814)
  docs/changelog.rst
  geotrek/api/mobile/serializers/common.py
  geotrek/api/tests/test_mobile/test_serializers.py
  geotrek/api/tests/test_mobile/test_sync_mobile.py
Labels: 🐛 bug

#4038 Hotfix CI: update E2E test to docker compose v2
  .github/workflows/test.yml
Labels: 👷 CI

#4037 📝 Review changelog 2.104.0
  docs/changelog.rst
Labels: 📝 Documentation

#4040 Static pages doc - Improve relative image path
  docs/usage/static-pages.rst
Labels: 📝 Documentation

#4042 Set MenuItem `open_in_new_tab` to False for page target
  docs/changelog.rst
  geotrek/flatpages/migrations/0015_set_open_in_new_tab_false_for_page_target.py
Labels: 🐛 bug

#4041 Add new author in documentation
  docs/others/authors.rst
Labels: 📝 Documentation

#4045 New menu items with page target open it in same tab
  docs/changelog.rst
  geotrek/flatpages/static/flatpages/js/menu_item_fieldsets.js
Labels: 🐛 bug

#4048 Ensure migration steps for menu items can be run separately
  docs/changelog.rst
  geotrek/flatpages/migrations/0011_migrate_flatpage_data.py
Labels: 🐛 bug

#4049 🐛 [Fix] Blockquote style in flat pages can be saved
  docs/changelog.rst
  geotrek/flatpages/widgets.py
Labels: 🐛 bug

#4047 📝 Fix RST syntax in Documentation
  docs/changelog.rst
  docs/contribute/design.rst
  docs/contribute/development.rst
  docs/contribute/documentation.rst
  docs/contribute/translating.rst
  docs/install/advanced-configuration.rst
  docs/install/configuration.rst
  docs/install/import.rst
  docs/install/installation.rst
  docs/install/loading-data.rst
  docs/install/upgrade.rst
  docs/others/troubleshooting.rst
  docs/usage/apis.rst
  docs/usage/configuration-ttw.rst
  docs/usage/editing-objects.rst
  docs/usage/interfaces.rst
  docs/usage/management-modules.rst
  docs/usage/touristic-modules.rst
  docs/usage/tutorials.rst
Labels: 📝 Documentation

#4050 📝 Improve static pages documentation
  docs/changelog.rst
  docs/usage/static-pages.rst
Labels: 📝 Documentation

#4058 Remove some sync_rando doc for dev
  docs/contribute/development.rst
Labels: 📝 Documentation

#4056 🐛 [Fix] Fix crash on migrate when db username or dbname contains dash
  docs/changelog.rst
  geotrek/common/utils/postgresql.py
Labels: 🐛 bug

#4062 💫 feat: Add `report` model on Intervention filters in module list (ref #3972)
  docs/changelog.rst
  geotrek/maintenance/filters.py
Labels: 💫 Improvements

#4059 🐛 [BUG] Fix Intervention end date should only be mandatory in last step of Suricate Workflow (refs #3825)
  docs/changelog.rst
  geotrek/feedback/locale/de/LC_MESSAGES/django.po
  geotrek/feedback/locale/en/LC_MESSAGES/django.po
  geotrek/feedback/tests/test_forms.py
  geotrek/maintenance/forms.py
  geotrek/maintenance/locale/de/LC_MESSAGES/django.po
  geotrek/maintenance/locale/en/LC_MESSAGES/django.po
  geotrek/maintenance/locale/es/LC_MESSAGES/django.po
  geotrek/maintenance/locale/fr/LC_MESSAGES/django.po
  geotrek/maintenance/locale/it/LC_MESSAGES/django.po
  geotrek/maintenance/locale/nl/LC_MESSAGES/django.po
  geotrek/maintenance/views.py
Labels: 🐛 bug

#4061 🐛 fix: change label filter intervention contractors and filter null value on project contractors detail view (ref #3820)
  docs/changelog.rst
  geotrek/maintenance/filters.py
  geotrek/maintenance/models.py
Labels: 🐛 bug

#4072 Sort attachments in API V2 for Outdoor Sites and Touristic Contents (refs #4071)
  docs/changelog.rst
  geotrek/api/v2/serializers.py
Labels: 🐛 bug

#4078 💫 [IMPR] Homogenize structure field in APIv2 to always return ids (refs #3007)
  docs/changelog.rst
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/serializers.py
Labels: 💫 Improvements

#4077 💫 [IMPR] Add structures to Aggregator (refs #3569)
  docs/changelog.rst
  geotrek/common/tests/test_parsers.py
  geotrek/infrastructure/parsers.py
  geotrek/infrastructure/tests/data/geotrek_parser_v2/infrastructure.json
  geotrek/infrastructure/tests/data/geotrek_parser_v2/structure.json
  geotrek/infrastructure/tests/test_parsers.py
  geotrek/outdoor/parsers.py
  geotrek/outdoor/tests/data/geotrek_parser_v2/structure.json
  geotrek/outdoor/tests/test_parsers.py
  geotrek/signage/parsers.py
  geotrek/signage/tests/data/geotrek_parser_v2/signage.json
  geotrek/signage/tests/data/geotrek_parser_v2/structure.json
  geotrek/signage/tests/test_parsers.py
  geotrek/tourism/parsers.py
  geotrek/tourism/tests/data/geotrek_parser_v2/structure.json
  geotrek/tourism/tests/test_parsers.py
  geotrek/trekking/parsers.py
  geotrek/trekking/tests/data/geotrek_parser_v2/poi.json
  geotrek/trekking/tests/data/geotrek_parser_v2/service.json
  geotrek/trekking/tests/data/geotrek_parser_v2/structure.json
  geotrek/trekking/tests/test_parsers.py
Labels: 💫 Improvements

#4080 🐛 [BUG] Expose missing Sources in APIv2 (refs #4079)
  docs/changelog.rst
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/filters.py
  geotrek/api/v2/views/common.py
Labels: 🐛 bug

#4081 📝 [DOC] Add update.sh to docker doc
  docs/changelog.rst
  docs/install/installation.rst
Labels: 📝 Documentation
