Repository GeotrekCE/Geotrek-admin, pull requests merged in 2024-07, with the labels that each got.

#4204 🐛 [BUG] Fix Reports attachments and default values (refs #4085)
  docs/changelog.rst
  geotrek/common/mixins/managers.py
  geotrek/common/templates/common/attachment_list.html
  geotrek/feedback/migrations/0044_auto_20240619_0810.py
  geotrek/feedback/templates/feedback/sql/post_90_defaults.sql
  requirements.txt
Labels: 🐛 bug

#4211 Too long linestring can't store elevation chart in default cache
  docs/changelog.rst
  geotrek/altimetry/views.py
Labels: 🐛 bug

#4217 Fix github action using node 20 instead of 16
  .github/workflows/test.yml
Labels: 👷 CI

#4225 bump to mapentity 8.9.2
  requirements.txt
Labels: dependencies, python

#4106 🐛 [FIX] Empty linetring in reorder_topology cmd (#4092)
  docs/changelog.rst
  geotrek/core/management/commands/reorder_topologies.py
Labels: 🐛 bug

#4084 💫 feat: change infrastructure condition field to ManyToMany field (#3970)
  docs/changelog.rst
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/serializers.py
  geotrek/api/v2/views/infrastructure.py
  geotrek/infrastructure/filters.py
  geotrek/infrastructure/forms.py
  geotrek/infrastructure/locale/de/LC_MESSAGES/django.po
  geotrek/infrastructure/locale/en/LC_MESSAGES/django.po
  geotrek/infrastructure/locale/es/LC_MESSAGES/django.po
  geotrek/infrastructure/locale/fr/LC_MESSAGES/django.po
  geotrek/infrastructure/locale/it/LC_MESSAGES/django.po
  geotrek/infrastructure/locale/nl/LC_MESSAGES/django.po
  geotrek/infrastructure/management/commands/loadinfrastructure.py
  geotrek/infrastructure/migrations/0039_infrastructure_conditions.py
  geotrek/infrastructure/migrations/0040_remove_infrastructure_condition.py
  geotrek/infrastructure/models.py
  geotrek/infrastructure/serializers.py
  geotrek/infrastructure/templates/infrastructure/infrastructure_detail_attributes.html
  geotrek/infrastructure/templates/infrastructure/sql/post_10_views.sql
  geotrek/infrastructure/tests/data/infrastructure.dbf
  geotrek/infrastructure/tests/data/infrastructure.qix
  geotrek/infrastructure/tests/factories.py
  geotrek/infrastructure/tests/test_command_loadinfrastructure.py
  geotrek/infrastructure/tests/test_views.py
  geotrek/infrastructure/views.py
  geotrek/maintenance/tests/test_views.py
Labels: 💫 Improvements

#4090 Prevent Pillow Decompressed Data Too Large Error from interrupting Parsers
  docs/changelog.rst
  geotrek/common/parsers.py
  geotrek/common/tests/test_parsers.py
Labels: 🐛 bug
