Repository GeotrekCE/Geotrek-admin, pull requests merged in 2024-06, with the labels that each got.

#4132 [📝 Documentation] Add details about dynamic segmentation for POIs
  docs/changelog.rst
  docs/usage/touristic-modules.rst
Labels: 📝 Documentation

#4162 Force default language and content translation in tests to English
  .github/workflows/test.yml
Labels: ✅ Tests

#4161 Update to django-leaflet fully compatible with Django 4.2
  requirements.txt
Labels: dependencies, python

#4135 ✨ [FEAT] Make email optional in Report form (refs #4085)
  docs/changelog.rst
  docs/install/advanced-configuration.rst
  geotrek/feedback/forms.py
  geotrek/feedback/locale/de/LC_MESSAGES/django.po
  geotrek/feedback/locale/en/LC_MESSAGES/django.po
  geotrek/feedback/locale/es/LC_MESSAGES/django.po
  geotrek/feedback/locale/fr/LC_MESSAGES/django.po
  geotrek/feedback/locale/it/LC_MESSAGES/django.po
  geotrek/feedback/locale/nl/LC_MESSAGES/django.po
  geotrek/feedback/migrations/0042_alter_report_email.py
  geotrek/feedback/models.py
  geotrek/feedback/templates/feedback/report_email.txt
  geotrek/feedback/tests/test_email.py
  geotrek/feedback/tests/test_forms.py
  geotrek/feedback/tests/test_suricate_sync.py
  geotrek/feedback/tests/test_views.py
  geotrek/feedback/views.py
Labels: ✨ Feature

#4172 Bump to django-mapentity 8.9.0
  docs/changelog.rst
  geotrek/common/tests/__init__.py
  geotrek/core/templates/core/path_detail.odt
  requirements.txt
Labels: dependencies, python

#4141 ✨ [FEAT] Add provider field and filter to Report (refs #4085)
  docs/changelog.rst
  docs/install/advanced-configuration.rst
  geotrek/api/v2/serializers.py
  geotrek/common/mixins/managers.py
  geotrek/feedback/filters.py
  geotrek/feedback/forms.py
  geotrek/feedback/locale/de/LC_MESSAGES/django.po
  geotrek/feedback/locale/en/LC_MESSAGES/django.po
  geotrek/feedback/locale/es/LC_MESSAGES/django.po
  geotrek/feedback/locale/fr/LC_MESSAGES/django.po
  geotrek/feedback/locale/it/LC_MESSAGES/django.po
  geotrek/feedback/locale/nl/LC_MESSAGES/django.po
  geotrek/feedback/managers.py
  geotrek/feedback/migrations/0043_report_provider.py
  geotrek/feedback/models.py
  geotrek/feedback/parsers.py
  geotrek/feedback/templates/feedback/report_detail_attributes.html
  geotrek/feedback/templates/feedback/report_email.txt
  geotrek/feedback/templates/feedback/sql/post_10_views.sql
  geotrek/feedback/templates/feedback/sql/post_90_defaults.sql
  geotrek/feedback/views.py
Labels: ✨ Feature

#4182 📝 [Documentation] Upgrade doc / PG upgrade review
  docs/changelog.rst
  docs/install/upgrade.rst
Labels: 📝 Documentation

#4189 Fix length filter on mobile
  docs/changelog.rst
  docs/install/advanced-configuration.rst
  geotrek/api/mobile/views/common.py
  geotrek/settings/base.py
Labels: 🐛 bug
