Repository GeotrekCE/Geotrek-admin, pull requests merged in 2024-03, with the labels that each got.

#3971 Update favicon with new logo
  docs/changelog.rst
  geotrek/static/images/favicon.png
Labels: 💫 Improvements

#3982 🐛 [BUG] Add missing translation for 'end date' in Intervention form (refs #3825)
  docs/changelog.rst
  geotrek/maintenance/forms.py
Labels: 🐛 bug

#3892 Add geometry to v_projects
  docs/changelog.rst
  geotrek/maintenance/templates/maintenance/sql/post_20_views.sql
Labels: 💫 Improvements

#3856 🐛 [Bug fix] Fix error in `cities` cache key prefix
  docs/changelog.rst
  geotrek/core/tests/test_views.py
  geotrek/tourism/tests/test_functional.py
  geotrek/zoning/mixins.py
Labels: 🐛 bug

#3984 Add `check_versions` command
  docs/changelog.rst
  docs/others/troubleshooting.rst
  geotrek/common/management/commands/check_versions.py
  geotrek/common/tests/test_commands.py
Labels: ✨ Feature

#3993 fix CI cache
  .github/actions/python-cache-requirements/action.yml
  .github/workflows/dependencies.yml
  .github/workflows/test.yml
Labels: 👷 CI

#3998 🚑 [HOT] Revert 'portals' filter on outdoor_rating endpoint (fix #3997)
  docs/changelog.rst
  geotrek/api/v2/filters.py
  geotrek/api/v2/views/outdoor.py
Labels: 🚑 Hotfix

#3992 Add PostgreSQL version info and upgrade in documentation
  docs/index.rst
  docs/install/docker.rst
  docs/install/installation.rst
  docs/install/upgrade.rst
Labels: 📝 Documentation

#4002 Fix fonts in weasyprint PDF (docker image only)
  docker/Dockerfile
  docs/changelog.rst
Labels: 🚑 Hotfix

#4001 Bump mapentity from 8.7.0 to 8.7.1
  docs/changelog.rst
  geotrek/tourism/tests/test_views.py
  requirements.txt
Labels: dependencies, python

#4004 Do not display deleted lames on signages (fix #4003)
  docs/changelog.rst
  geotrek/signage/models.py
Labels: 🐛 bug

#4010 Improve postgres upgrade doc
  docs/install/upgrade.rst
Labels: 📝 Documentation

#4013 bump to mapentity 8.7.2
  docs/changelog.rst
  requirements.txt
Labels: dependencies, python

#4014 Bump django-debug-toolbar to 4.3.0
  dev-requirements.txt
Labels: dependencies, python

#4021 Fix api crash when using an svg file for information desks (fixes #3860)
  debian/rules
  docs/changelog.rst
  geotrek/api/tests/test_v2.py
  requirements.txt
  setup.py
Labels: 🐛 bug, dependencies, python
