Repository GeotrekCE/Geotrek-admin, pull requests merged in 2024-10, with the labels that each got.

#4322 Use new Django Crispy Form
  docker-compose.yml
  docs/changelog.rst
  geotrek/common/forms.py
  geotrek/feedback/tests/test_email.py
  geotrek/feedback/tests/test_forms.py
  geotrek/feedback/tests/test_suricate_sync.py
  geotrek/settings/base.py
  geotrek/static/images/logo-login.png
  requirements.txt
Labels: dependencies, python

#4324 Support python 3.10 and update Docker image
  .github/workflows/test.yml
  debian/conffiles
  debian/control
  debian/geotrek-admin.triggers
  dev-requirements.txt
  docker-compose.yml
  docker/Dockerfile
  docker/Dockerfile.debian.builder
  docker/scripts/entrypoint.sh
  docs/changelog.rst
  geotrek/common/parsers.py
  geotrek/settings/env_tests.py
  requirements.txt
  setup.py
Labels: ⚡ Performances, 💫 Improvements, 🏗️ Maintenance

#4327 Fix and update deprecated Github actions
  .github/workflows/test.yml
Labels: github_actions, 👷 CI

#4330 💫 [IMPR] Improve default configuration and documentation for docker
  .env.dist
  docs/install/installation.rst
Labels: 💫 Improvements

#4337 📝 [Documentation] Doc dev quick start improvement
  docs/changelog.rst
  docs/contribute/development.rst
Labels: 📝 Documentation

#4329 Fix 'loadinfrastructure' condition adding to infra without 'eid-field' option
  geotrek/infrastructure/management/commands/loadinfrastructure.py
Labels: 🐛 bug

#4338 🐛 [BUG] Fix errors in Aggregator when retrieving unpublished Route Steps (refs #3569)
  docs/changelog.rst
  geotrek/api/v2/views/trekking.py
  geotrek/common/tests/mixins.py
  geotrek/common/tests/test_parsers.py
  geotrek/trekking/parsers.py
  geotrek/trekking/tests/data/geotrek_parser_v2/trek_children.json
  geotrek/trekking/tests/data/geotrek_parser_v2/trek_children_do_not_exist.json
  geotrek/trekking/tests/data/geotrek_parser_v2/trek_network.json
  geotrek/trekking/tests/data/geotrek_parser_v2/trek_published_step.json
  geotrek/trekking/tests/data/geotrek_parser_v2/trek_route.json
  geotrek/trekking/tests/data/geotrek_parser_v2/trek_unpublished_practice.json
  geotrek/trekking/tests/data/geotrek_parser_v2/trek_unpublished_practice_not_found.json
  geotrek/trekking/tests/data/geotrek_parser_v2/trek_unpublished_step.json
  geotrek/trekking/tests/data/geotrek_parser_v2/trek_unpublished_structure.json
  geotrek/trekking/tests/test_parsers.py
Labels: 🐛 bug

#4339 💫 Modify text for 'add image gallery' button for flatpages
  docs/changelog.rst
  geotrek/flatpages/locale/de/LC_MESSAGES/django.po
  geotrek/flatpages/locale/en/LC_MESSAGES/django.po
  geotrek/flatpages/locale/es/LC_MESSAGES/django.po
  geotrek/flatpages/locale/fr/LC_MESSAGES/django.po
  geotrek/flatpages/locale/it/LC_MESSAGES/django.po
  geotrek/flatpages/locale/nl/LC_MESSAGES/django.po
  geotrek/flatpages/templates/flatpages/translations_js.html
Labels: 💫 Improvements
