Repository GeotrekCE/Geotrek-admin, pull requests merged in 2024-08, with the labels that each got.

#4254 🐛 [BUG] Fix error on APIv2 for Signages with pictograms (refs #3839)
  docs/changelog.rst
  geotrek/api/v2/serializers.py
Labels: 🐛 bug

#4246 ✨ [FEAT] Add Annotation Category model and API for HD Views (refs #4032)
  docs/changelog.rst
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/serializers.py
  geotrek/api/v2/urls.py
  geotrek/api/v2/views/__init__.py
  geotrek/api/v2/views/common.py
  geotrek/common/admin.py
  geotrek/common/forms.py
  geotrek/common/locale/de/LC_MESSAGES/django.po
  geotrek/common/locale/en/LC_MESSAGES/django.po
  geotrek/common/locale/es/LC_MESSAGES/django.po
  geotrek/common/locale/fr/LC_MESSAGES/django.po
  geotrek/common/locale/it/LC_MESSAGES/django.po
  geotrek/common/locale/nl/LC_MESSAGES/django.po
  geotrek/common/migrations/0037_annotationcategory_and_more.py
  geotrek/common/models.py
  geotrek/common/static/common/js/annotations.js
  geotrek/common/static/common/style.css
  geotrek/common/templates/common/hdviewpoint_annotation_form.html
  geotrek/common/templates/common/sql/post_90_defaults.sql
  geotrek/common/tests/factories.py
  geotrek/common/tests/test_admin.py
  geotrek/common/tests/test_forms.py
  geotrek/common/translation.py
Labels: ✨ Feature

#4258 ⬆ [DEP] Bump Django from 4.2.14 to 4.2.15
  dev-requirements.txt
  docs/changelog.rst
  requirements.txt
Labels: dependencies

#4270 [📝 Documentation] add authors columns in displayed list views and export
  docs/changelog.rst
  docs/install/advanced-configuration.rst
Labels: 📝 Documentation

#4180 Move from `env_file` to `dotenv` (deprecated)
  docs/changelog.rst
  geotrek/settings/base.py
  requirements.txt
  setup.py
Labels: dependencies, python

#4275 🐛 [BUG] Fix APIv2 exception on HD Views without Annotations (#4032)
  docs/changelog.rst
  geotrek/api/v2/serializers.py
Labels: 🐛 bug

#4266 💫 [IMPR] Allow displaying assigned_user field in Report Form via conf if needed (#4085)
  docs/changelog.rst
  docs/install/advanced-configuration.rst
  geotrek/feedback/forms.py
  geotrek/feedback/tests/test_suricate_sync.py
  geotrek/settings/base.py
Labels: 💫 Improvements

#4277 ⚡ [PERF] Optimize some queries
  docs/changelog.rst
  geotrek/land/filters.py
  geotrek/land/models.py
  geotrek/maintenance/filters.py
  geotrek/outdoor/templatetags/outdoor_tags.py
  geotrek/tourism/filters.py
  geotrek/tourism/templatetags/tourism_tags.py
  geotrek/trekking/models.py
  geotrek/trekking/templatetags/trekking_tags.py
  geotrek/trekking/views.py
Labels: ⚡ Performances

#3877 Improve documentation for sensitivity module (refs #3876)
  docs/changelog.rst
  docs/data-model/sensitivity.pdf
  docs/install/advanced-configuration.rst
  docs/install/import.rst
  docs/usage/apis.rst
Labels: 📝 Documentation

#4285 filter out deleted services in API response
  docs/changelog.rst
  geotrek/api/v2/views/trekking.py
Labels: 🐛 bug
