Repository GeotrekCE/Geotrek-admin, pull requests merged in 2024-05, with the labels that each got.

#4076 💥 Remove unused 'Related Treks' concept (refs #3750)
  docs/changelog.rst
  docs/install/advanced-configuration.rst
  geotrek/api/tests/test_v2.py
  geotrek/trekking/forms.py
  geotrek/trekking/locale/de/LC_MESSAGES/django.po
  geotrek/trekking/locale/en/LC_MESSAGES/django.po
  geotrek/trekking/locale/es/LC_MESSAGES/django.po
  geotrek/trekking/locale/fr/LC_MESSAGES/django.po
  geotrek/trekking/locale/it/LC_MESSAGES/django.po
  geotrek/trekking/locale/nl/LC_MESSAGES/django.po
  geotrek/trekking/managers.py
  geotrek/trekking/migrations/0049_auto_20240417_1519.py
  geotrek/trekking/models.py
  geotrek/trekking/parsers.py
  geotrek/trekking/templates/trekking/sql/post_20_treks.sql
  geotrek/trekking/templates/trekking/sql/post_90_defaults.sql
  geotrek/trekking/templates/trekking/trek_detail_attributes.html
  geotrek/trekking/templates/trekking/trek_form.html
  geotrek/trekking/tests/factories.py
  geotrek/trekking/tests/test_trek_relationship.py
  geotrek/trekking/tests/test_views.py
  geotrek/trekking/views.py
Labels: 💥 Breaking changes

#4094 Set MenuItem `open_in_new_tab` to False when no target (#4093)
  docs/changelog.rst
  geotrek/flatpages/static/flatpages/js/menu_item_fieldsets.js
Labels: 🐛 bug

#4101 🚑 [HotFix] Bump to mapentity 8.8.1 to get a fix
  docs/changelog.rst
  requirements.txt
Labels: 🚑 Hotfix

#4105 🚑 [HOT] Improve performance on retrieving Sources in APIv2 #4079
  docs/changelog.rst
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/filters.py
Labels: 🚑 Hotfix

#4108 [📝 Documentation] Improvements about upgrading debian version and remove screenshot sensitivity parameter
  docs/changelog.rst
  docs/install/advanced-configuration.rst
  docs/install/upgrade.rst
Labels: 📝 Documentation

#3983 Bump to django 4.2 and run django-upgrade
  .github/actions/python-cache-requirements/action.yml
  .github/workflows/test.yml
  cypress/integration/nav_authent.js
  cypress/nginx.conf
  dev-requirements.txt
  docker-compose.yml
  geotrek/altimetry/__init__.py
  geotrek/api/tests/test_mobile/test_api_mobile.py
  geotrek/api/tests/test_mobile/test_api_mobile_flatpage.py
  geotrek/api/tests/test_mobile/test_api_mobile_settings.py
  geotrek/api/tests/test_v2.py
  geotrek/authent/__init__.py
  geotrek/authent/middleware.py
  geotrek/cirkwi/__init__.py
  geotrek/cirkwi/admin.py
  geotrek/cirkwi/serializers.py
  geotrek/cirkwi/tests/test_views.py
  geotrek/common/__init__.py
  geotrek/common/admin.py
  geotrek/common/tests/test_views.py
  geotrek/core/__init__.py
  geotrek/core/admin.py
  geotrek/diving/__init__.py
  geotrek/feedback/__init__.py
  geotrek/feedback/tests/test_forms.py
  geotrek/flatpages/__init__.py
  geotrek/infrastructure/__init__.py
  geotrek/infrastructure/admin.py
  geotrek/land/__init__.py
  geotrek/land/admin.py
  geotrek/maintenance/__init__.py
  geotrek/maintenance/admin.py
  geotrek/maintenance/tests/test_models.py
  geotrek/outdoor/__init__.py
  geotrek/outdoor/admin.py
  geotrek/outdoor/tests/test_forms.py
  geotrek/sensitivity/__init__.py
  geotrek/sensitivity/admin.py
  geotrek/sensitivity/tests/test_parsers.py
  geotrek/sensitivity/tests/test_views.py
  geotrek/sensitivity/views.py
  geotrek/settings/base.py
  geotrek/settings/env_tests.py
  geotrek/signage/__init__.py
  geotrek/signage/admin.py
  geotrek/tourism/__init__.py
  geotrek/tourism/tests/test_parsers.py
  geotrek/trekking/__init__.py
  geotrek/trekking/admin.py
  geotrek/trekking/tests/test_trek_forms.py
  geotrek/trekking/tests/test_views.py
  geotrek/zoning/__init__.py
  geotrek/zoning/admin.py
  requirements.txt
  setup.py
Labels: dependencies, python, 💥 Breaking changes

#4109 Bump to django 4.2.13
  .github/actions/python-cache-requirements/action.yml
  dev-requirements.txt
  geotrek/api/tests/test_mobile/test_sync_mobile.py
  geotrek/common/tests/__init__.py
  geotrek/feedback/tests/test_commands.py
  geotrek/feedback/tests/test_email.py
  requirements.txt
Labels: dependencies, python

#4112 [📝 Documentation] Put back SHOW_SENSITIVE_AREAS_ON_MAP_SCREENSHOT parameter
  .github/workflows/doc.yml
  docs/changelog.rst
  docs/install/advanced-configuration.rst
Labels: 📝 Documentation

#4110 bump to gunicorn 22.0.0
  requirements.txt
Labels: dependencies, python

#4100 Fix v_treks view duplicated when multiple sources (refs #4099)
  docs/changelog.rst
  geotrek/trekking/templates/trekking/sql/post_30_views.sql
Labels: 🐛 bug

#4111 bump to jinja2 3.1.4
  docs/requirements.txt
  requirements.txt
Labels: dependencies, python

#4117 Fix tests to avoid random errors
  geotrek/feedback/management/commands/erase_emails.py
  geotrek/feedback/tests/test_commands.py
  geotrek/feedback/tests/test_suricate_sync.py
Labels: ✅ Tests

#4118 fix tests
  geotrek/feedback/tests/test_email.py
  geotrek/flatpages/migrations/0010_create_model_MenuItem.py
  geotrek/maintenance/tests/test_views.py
Labels: ✅ Tests

#4126 💫 [IMPR] ApidaeTrekParser now imports `membreProprietaire` as structure
  docs/changelog.rst
  geotrek/trekking/parsers.py
  geotrek/trekking/tests/test_parsers.py
Labels: 💫 Improvements

#4125 fix flaky tests
  geotrek/api/management/commands/sync_mobile.py
  geotrek/authent/tests/test_backend.py
  geotrek/common/tests/__init__.py
  geotrek/feedback/tests/test_forms.py
  geotrek/feedback/tests/test_suricate_sync.py
  geotrek/feedback/tests/test_template_tags.py
  geotrek/feedback/views.py
  geotrek/settings/env_tests.py
  requirements.txt
Labels: ✅ Tests

#4120 bump celery 5.4.0
  geotrek/api/management/commands/sync_mobile.py
  requirements.txt
Labels: dependencies, python

#4128 bump django-compressor
  requirements.txt
Labels: dependencies, python

#4131 🐛 fix: Prevent trek map screenshot error if type of associated information desk have not pictogram
  docs/changelog.rst
  geotrek/trekking/templates/trekking/trek_detail.html
Labels: 🐛 bug

#4133 🌐 [TRANS] Fix update translations
  geotrek/common/locale/de/LC_MESSAGES/django.po
  geotrek/common/locale/en/LC_MESSAGES/django.po
  geotrek/common/locale/es/LC_MESSAGES/django.po
  geotrek/common/locale/fr/LC_MESSAGES/django.po
  geotrek/common/locale/it/LC_MESSAGES/django.po
  geotrek/common/locale/nl/LC_MESSAGES/django.po
  geotrek/maintenance/locale/de/LC_MESSAGES/django.po
  geotrek/maintenance/locale/en/LC_MESSAGES/django.po
  geotrek/maintenance/locale/es/LC_MESSAGES/django.po
  geotrek/maintenance/locale/fr/LC_MESSAGES/django.po
  geotrek/maintenance/locale/it/LC_MESSAGES/django.po
  geotrek/maintenance/locale/nl/LC_MESSAGES/django.po
  geotrek/trekking/locale/de/LC_MESSAGES/django.po
  geotrek/trekking/locale/en/LC_MESSAGES/django.po
  geotrek/trekking/locale/es/LC_MESSAGES/django.po
  geotrek/trekking/locale/fr/LC_MESSAGES/django.po
  geotrek/trekking/locale/it/LC_MESSAGES/django.po
  geotrek/trekking/locale/nl/LC_MESSAGES/django.po
Labels: 🌐 Translations

#4138 Fix tests with tanslation problems
  geotrek/api/management/commands/sync_mobile.py
  geotrek/common/management/commands/unset_structure.py
  geotrek/flatpages/migrations/0011_migrate_flatpage_data.py
  geotrek/trekking/tests/test_translation.py
Labels: ✅ Tests

#4144 Fix CI to allow using last codecov action on reports generated in bionic
  .github/workflows/test.yml
Labels: 👷 CI

#4142 [FIX] Exclude deleted areas from OpenAir export (#4140)
  docs/changelog.rst
  geotrek/sensitivity/views.py
Labels: 💫 Improvements

#4145 Fix flaky test in sync_mobile
  geotrek/api/tests/test_mobile/test_sync_mobile.py
Labels: ✅ Tests
