Repository GeotrekCE/Geotrek-admin, pull requests merged in 2024-01, with the labels that each got.

#3853 Add end date to Intervention model (refs #3825)
  docs/changelog.rst
  docs/install/advanced-configuration.rst
  geotrek/feedback/fixtures/test-integration.json
  geotrek/feedback/static/feedback/workflow.js
  geotrek/feedback/templates/feedback/report_detail_attributes.html
  geotrek/feedback/templatetags/feedback_tags.py
  geotrek/feedback/tests/test_forms.py
  geotrek/feedback/tests/test_template_tags.py
  geotrek/infrastructure/filters.py
  geotrek/infrastructure/tests/test_filters.py
  geotrek/maintenance/filters.py
  geotrek/maintenance/forms.py
  geotrek/maintenance/locale/de/LC_MESSAGES/django.po
  geotrek/maintenance/locale/en/LC_MESSAGES/django.po
  geotrek/maintenance/locale/es/LC_MESSAGES/django.po
  geotrek/maintenance/locale/fr/LC_MESSAGES/django.po
  geotrek/maintenance/locale/it/LC_MESSAGES/django.po
  geotrek/maintenance/locale/nl/LC_MESSAGES/django.po
  geotrek/maintenance/managers.py
  geotrek/maintenance/migrations/0024_auto_20231206_1627.py
  geotrek/maintenance/migrations/0025_remove_intervention_date.py
  geotrek/maintenance/models.py
  geotrek/maintenance/templates/maintenance/intervention_detail.html
  geotrek/maintenance/templates/maintenance/intervention_form.html
  geotrek/maintenance/templates/maintenance/maintenance_detail_fragment.html
  geotrek/maintenance/templates/maintenance/sql/post_20_views.sql
  geotrek/maintenance/templates/maintenance/sql/post_90_defaults.sql
  geotrek/maintenance/tests/factories.py
  geotrek/maintenance/tests/test_forms.py
  geotrek/maintenance/tests/test_views.py
  geotrek/maintenance/views.py
  geotrek/signage/filters.py
Labels: ✨ Feature

#3874 📝 [Documentation] - Improve documentation about suricate workflow (refs #3870)
  docs/changelog.rst
  docs/images/advanced-configuration/suricate.png
  docs/install/advanced-configuration.rst
Labels: scope: docs, suricate-workflow, 📝 Documentation

#3840 Update documentation to match changes of IGN
  docs/changelog.rst
  docs/install/advanced-configuration.rst
  geotrek/common/tests/__init__.py
  geotrek/settings/base.py
  tools/check_ign_key.sh
Labels: 📝 Documentation

#3882 Maintenance appears several times on some zoning filters #3881
  docs/changelog.rst
  geotrek/maintenance/filters.py
Labels: 🐛 bug

#3868 🐛 [BUG] Fix sublanguage usage (refs #3801)
  docs/changelog.rst
  geotrek/api/management/commands/sync_mobile.py
  geotrek/api/tests/test_mobile/test_sync_mobile.py
  geotrek/api/v2/filters.py
  geotrek/api/v2/utils.py
  geotrek/api/v2/views/trekking.py
  geotrek/common/forms.py
  geotrek/common/management/commands/sync_rando.py
  geotrek/common/management/commands/update_post_migration_languages.py
  geotrek/common/migrations/0008_auto_20200228_1830.py
  geotrek/common/mixins/models.py
  geotrek/common/mixins/views.py
  geotrek/common/parsers.py
  geotrek/common/tests/test_sync.py
  geotrek/common/urls.py
  geotrek/common/utils/postgresql.py
  geotrek/common/views.py
  geotrek/diving/helpers_sync.py
  geotrek/diving/migrations/0004_auto_20200228_2153.py
  geotrek/diving/urls.py
  geotrek/feedback/urls.py
  geotrek/flatpages/forms.py
  geotrek/flatpages/migrations/0005_auto_20200228_2150.py
  geotrek/infrastructure/migrations/0028_infrastructure_published_translation.py
  geotrek/infrastructure/migrations/0029_auto_20220314_0912.py
  geotrek/infrastructure/migrations/0030_auto_20220314_1429.py
  geotrek/infrastructure/urls.py
  geotrek/outdoor/models.py
  geotrek/outdoor/urls.py
  geotrek/sensitivity/migrations/0018_auto_20200228_2152.py
  geotrek/sensitivity/urls.py
  geotrek/signage/migrations/0022_auto_20220314_1048.py
  geotrek/signage/migrations/0023_auto_20220314_1441.py
  geotrek/signage/urls.py
  geotrek/tourism/managers.py
  geotrek/tourism/migrations/0010_auto_20200228_2152.py
  geotrek/tourism/migrations/0033_auto_20220929_0840.py
  geotrek/tourism/urls.py
  geotrek/trekking/forms.py
  geotrek/trekking/helpers_sync.py
  geotrek/trekking/migrations/0014_auto_20200228_2127.py
  geotrek/trekking/parsers.py
  geotrek/trekking/urls.py
  requirements.txt
Labels: 🐛 bug

#3648 Add command to identify and merge some paths #3607
  docs/changelog.rst
  docs/install/import.rst
  geotrek/core/management/commands/merge_segmented_paths.py
  geotrek/core/tests/test_commands.py
Labels: ✨ Feature

#3883 Display only related project Intervention on map #3878
  docs/changelog.rst
  geotrek/maintenance/templates/maintenance/project_detail.html
Labels: 🐛 bug

#3891 Improve troubleshouting section with Document / Map capture generation
  docs/index.rst
  docs/install/troubleshooting.rst
  docs/troubleshooting.rst
Labels: 📝 Documentation

#3888 Improve perfs for spatial intersection for sql views (refs : #3600)
  docs/changelog.rst
  geotrek/core/templates/core/sql/post_60_views.sql
  geotrek/feedback/templates/feedback/sql/post_10_views.sql
  geotrek/infrastructure/templates/infrastructure/sql/post_10_views.sql
  geotrek/maintenance/templates/maintenance/sql/post_20_views.sql
  geotrek/outdoor/templates/outdoor/sql/post_20_views.sql
  geotrek/sensitivity/templates/sensitivity/sql/post_10_views.sql
  geotrek/signage/templates/signage/sql/post_10_views.sql
  geotrek/tourism/templates/tourism/sql/post_20_views.sql
  geotrek/trekking/templates/trekking/sql/post_30_views.sql
Labels: 💫 Improvements

#3907 Revert https on default map tiles
  geotrek/settings/base.py
Labels: 👷 CI, 🚑 Hotfix

#3908 Improve mocking tiles in cypress tests
  cypress/integration/nav_authent.js
  cypress/integration/nav_b_language.js
  cypress/integration/nav_create_path.js
  cypress/integration/nav_create_signage.js
  cypress/integration/nav_create_trek.js
  cypress/integration/nav_reports_workflow.js
  cypress/integration/nav_tabs.js
  cypress/integration/nav_tourism.js
  cypress/support/commands.js
Labels: ✅ Tests, 👷 CI

#3899 💫 [FIX] Allow Apidae Trek parser to handle traces not in utf-8
  docs/changelog.rst
  geotrek/common/utils/file_infos.py
  geotrek/trekking/parsers.py
  geotrek/trekking/tests/data/file_bad_encoding.kml
  geotrek/trekking/tests/data/file_good_encoding.kml
  geotrek/trekking/tests/test_parsers.py
  requirements.txt
  setup.py
Labels: 💫 Improvements
