Repository GeotrekCE/Geotrek-admin, pull requests merged in 2024-12, with the labels that each got.

#3968 ✨ [FEAT] Add CirkwiParser to retrieve Treks and Touristic Contents (refs #3947)
  docs/changelog.rst
  geotrek/cirkwi/locale/de/LC_MESSAGES/django.po
  geotrek/cirkwi/locale/en/LC_MESSAGES/django.po
  geotrek/cirkwi/locale/es/LC_MESSAGES/django.po
  geotrek/cirkwi/locale/fr/LC_MESSAGES/django.po
  geotrek/cirkwi/locale/it/LC_MESSAGES/django.po
  geotrek/cirkwi/locale/nl/LC_MESSAGES/django.po
  geotrek/cirkwi/parsers.py
  geotrek/cirkwi/tests/data/circuits.xml
  geotrek/cirkwi/tests/data/circuits_updated.xml
  geotrek/cirkwi/tests/data/circuits_wrong_locomotion_and_difficulty.xml
  geotrek/cirkwi/tests/data/poi.xml
  geotrek/cirkwi/tests/data/trek.gpx
  geotrek/cirkwi/tests/factories.py
  geotrek/cirkwi/tests/test_parsers.py
  geotrek/common/parsers.py
  geotrek/common/tests/test_utils.py
  geotrek/common/utils/parsers.py
  geotrek/trekking/parsers.py
  geotrek/trekking/tests/data/apidae_trek_parser/a_trek_with_bad_geom.json
  geotrek/trekking/tests/test_parsers.py
Labels: ✨ Feature

#4408 📝 [Documentation] Improve doc theme and update README
  README.md
  README.rst
  docs/_static/geotrek-admin.png
  docs/changelog.rst
  docs/conf.py
  docs/usage/apis.rst
  docs/usage/configuration-ttw.rst
Labels: 📝 Documentation

#4416 fix some flaky tests
  geotrek/maintenance/models.py
  geotrek/trekking/tests/test_models.py
Labels: ✅ Tests
