Repository GeotrekCE/Geotrek-admin, pull requests merged in 2024-09, with the labels that each got.

#4181 ApidaeTrekParser now fallbacks on trace filename extension if no extension property
  docs/changelog.rst
  geotrek/trekking/parsers.py
  geotrek/trekking/tests/data/apidae_trek_parser/trek_with_plan_with_no_extension_at_all.json
  geotrek/trekking/tests/data/apidae_trek_parser/trek_with_plan_without_extension_prop.json
  geotrek/trekking/tests/test_parsers.py
Labels: 🐛 bug

#4187 Fix : Apidae Trek parser now ignores when no linestring in GPX
  docs/changelog.rst
  geotrek/trekking/parsers.py
  geotrek/trekking/tests/data/apidae_trek_parser/trace_with_no_feature.gpx
  geotrek/trekking/tests/test_parsers.py
Labels: 🐛 bug

#4193 Fix ApidaeTrekParser duration import logic
  docs/changelog.rst
  geotrek/trekking/parsers.py
  geotrek/trekking/tests/test_parsers.py
Labels: 🐛 bug

#4202 Fix apidae trek parser multiple gpx features
  docs/changelog.rst
  geotrek/trekking/parsers.py
  geotrek/trekking/tests/data/apidae_trek_parser/trace_with_multiple_continuous_features.gpx
  geotrek/trekking/tests/data/apidae_trek_parser/trace_with_multiple_continuous_features_and_one_empty.gpx
  geotrek/trekking/tests/data/apidae_trek_parser/trace_with_multiple_not_continuous_features.gpx
  geotrek/trekking/tests/test_parsers.py
Labels: 💫 Improvements

#4203 Apidae tourism parser now handles missing contact properties
  docs/changelog.rst
  geotrek/tourism/parsers.py
Labels: 🐛 bug

#4205 Fix apidae trek parser no source website
  docs/changelog.rst
  geotrek/trekking/parsers.py
Labels: 🐛 bug

#4129 MenuItems with platform "Mobile" are now hidden on API (#4127)
  docs/changelog.rst
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/views/flatpages.py
Labels: 🐛 bug

#4290 📝 [Documentation] Add command line examples and templates for importing data
  docs/changelog.rst
  docs/files/import/cities.geojson
  docs/files/import/districts.geojson
  docs/files/import/infrastructure.geojson
  docs/files/import/paths.geojson
  docs/files/import/poi.geojson
  docs/files/import/restrictedareas.geojson
  docs/files/import/signage.geojson
  docs/install/import.rst
Labels: 📝 Documentation

#4278 ⚡ [PERF] Optimize Path Aggregation query in detail view
  docs/changelog.rst
  geotrek/core/models.py
Labels: ⚡ Performances

#4309 🐛 [BUG] Fix missing Annotation Categories in APIv2 for annotations other than Points (refs #4032)
  docs/changelog.rst
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/serializers.py
Labels: 🐛 bug

#4307 🐛 [BUG] Change default CORS configuration to 'always'
  conf/nginx.conf.in
  docs/changelog.rst
Labels: 🐛 bug
