Repository GeotrekCE/Geotrek-admin, pull requests merged in 2024-02, with the labels that each got.

#3886 ✨ [FEAT] Add UUIDs of parent and children Courses and Sites in APIv2 (refs #3569)
  docs/changelog.rst
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/mixins.py
  geotrek/api/v2/serializers.py
  geotrek/api/v2/views/outdoor.py
Labels: ✨ Feature

#3903 🐛 [FIX] Signage & Blade conditions translations + admin BladeCondition entry (#3847)
  docs/changelog.rst
  geotrek/signage/admin.py
  geotrek/signage/locale/de/LC_MESSAGES/django.po
  geotrek/signage/locale/en/LC_MESSAGES/django.po
  geotrek/signage/locale/es/LC_MESSAGES/django.po
  geotrek/signage/locale/fr/LC_MESSAGES/django.po
  geotrek/signage/locale/it/LC_MESSAGES/django.po
  geotrek/signage/locale/nl/LC_MESSAGES/django.po
  geotrek/signage/migrations/0036_auto_20231013_1326.py
Labels: 🐛 bug

#3943 Fix typo in docs/install/advanced-configuration.rst
  docs/install/advanced-configuration.rst
Labels: 📝 Documentation

#3919 🐛 [Fix] intervention date filter and add intervention years filter
  docs/changelog.rst
  geotrek/maintenance/filters.py
  geotrek/maintenance/locale/de/LC_MESSAGES/django.po
  geotrek/maintenance/locale/en/LC_MESSAGES/django.po
  geotrek/maintenance/locale/es/LC_MESSAGES/django.po
  geotrek/maintenance/locale/fr/LC_MESSAGES/django.po
  geotrek/maintenance/locale/it/LC_MESSAGES/django.po
  geotrek/maintenance/locale/nl/LC_MESSAGES/django.po
  geotrek/maintenance/managers.py
  geotrek/maintenance/static/maintenance/main.js
  geotrek/maintenance/tests/test_filters.py
  geotrek/maintenance/tests/test_managers.py
Labels: 🐛 bug

#3948 🚑 [HOTFIX] Remove workforce cost (#3824)
  docs/changelog.rst
  docs/install/advanced-configuration.rst
  geotrek/maintenance/forms.py
  geotrek/maintenance/locale/de/LC_MESSAGES/django.po
  geotrek/maintenance/locale/en/LC_MESSAGES/django.po
  geotrek/maintenance/locale/es/LC_MESSAGES/django.po
  geotrek/maintenance/locale/fr/LC_MESSAGES/django.po
  geotrek/maintenance/locale/it/LC_MESSAGES/django.po
  geotrek/maintenance/locale/nl/LC_MESSAGES/django.po
  geotrek/maintenance/migrations/0029_remove_intervention_workforce_cost.py
  geotrek/maintenance/models.py
  geotrek/maintenance/templates/maintenance/intervention_detail.html
  geotrek/maintenance/templates/maintenance/sql/post_20_views.sql
  geotrek/maintenance/templates/maintenance/sql/post_90_defaults.sql
  geotrek/maintenance/tests/test_models.py
  geotrek/maintenance/tests/test_views.py
  geotrek/maintenance/views.py
Labels: 🚑 Hotfix

#3958 ✨ [FEAT] Add filter to Cirkwi trek exports (refs #3947)
  docs/changelog.rst
  docs/usage/externals-apis.rst
  geotrek/cirkwi/filters.py
  geotrek/cirkwi/tests/test_filters.py
  geotrek/cirkwi/views.py
Labels: ✨ Feature

#3965 Touristic event organizers in many to many #3587
  docs/changelog.rst
  docs/install/advanced-configuration.rst
  geotrek/api/mobile/serializers/tourism.py
  geotrek/api/tests/test_mobile/test_api_mobile.py
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/filters.py
  geotrek/api/v2/serializers.py
  geotrek/api/v2/views/tourism.py
  geotrek/tourism/forms.py
  geotrek/tourism/locale/en/LC_MESSAGES/django.po
  geotrek/tourism/migrations/0050_auto_20231220_0952.py
  geotrek/tourism/migrations/0051_merge_20240229_1225.py
  geotrek/tourism/models.py
  geotrek/tourism/parsers.py
  geotrek/tourism/serializers.py
  geotrek/tourism/templates/tourism/sql/post_20_views.sql
  geotrek/tourism/templates/tourism/touristicevent_detail_attributes.html
  geotrek/tourism/tests/test_forms.py
  geotrek/tourism/tests/test_functional.py
  geotrek/tourism/tests/test_parsers.py
  geotrek/tourism/tests/test_views.py
  geotrek/tourism/views.py
Labels: 💫 Improvements

#3967 Bump mapentity from 8.6.2 to 8.7.0
  requirements.txt
Labels: dependencies, python
