Repository GeotrekCE/Geotrek-admin, pull requests merged in 2024-11, with the labels that each got.

#4348 Fix flaky tests
  Makefile
  geotrek/altimetry/helpers.py
  geotrek/altimetry/locale/de/LC_MESSAGES/django.po
  geotrek/altimetry/locale/en/LC_MESSAGES/django.po
  geotrek/altimetry/locale/es/LC_MESSAGES/django.po
  geotrek/altimetry/locale/fr/LC_MESSAGES/django.po
  geotrek/altimetry/locale/it/LC_MESSAGES/django.po
  geotrek/altimetry/locale/nl/LC_MESSAGES/django.po
  geotrek/altimetry/tests/test_elevation.py
  geotrek/api/management/commands/sync_mobile.py
  geotrek/api/mobile/serializers/trekking.py
  geotrek/api/tests/test_mobile/test_api_mobile.py
  geotrek/api/tests/test_mobile/test_api_mobile_flatpage.py
  geotrek/api/tests/test_mobile/test_api_mobile_settings.py
  geotrek/api/tests/test_mobile/test_sync_mobile.py
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/renderers.py
  geotrek/api/v2/views/common.py
  geotrek/api/v2/views/outdoor.py
  geotrek/api/v2/views/tourism.py
  geotrek/api/v2/views/trekking.py
  geotrek/cirkwi/serializers.py
  geotrek/cirkwi/tests/test_views.py
  geotrek/common/forms.py
  geotrek/common/middleware.py
  geotrek/common/mixins/models.py
  geotrek/common/parsers.py
  geotrek/common/tests/__init__.py
  geotrek/common/tests/test_admin.py
  geotrek/common/tests/test_parsers.py
  geotrek/common/tests/test_tags.py
  geotrek/common/tests/test_views.py
  geotrek/core/tests/test_models.py
  geotrek/diving/tests/test_models.py
  geotrek/diving/views.py
  geotrek/feedback/tests/test_commands.py
  geotrek/feedback/tests/test_suricate_sync.py
  geotrek/infrastructure/tests/test_parsers.py
  geotrek/maintenance/tests/test_forms.py
  geotrek/maintenance/tests/test_views.py
  geotrek/sensitivity/tests/test_parsers.py
  geotrek/settings/env_tests.py
  geotrek/signage/tests/test_parsers.py
  geotrek/tourism/tests/test_functional.py
  geotrek/tourism/tests/test_parsers.py
  geotrek/trekking/tests/factories.py
  geotrek/trekking/tests/test_models.py
  geotrek/trekking/tests/test_parsers.py
  geotrek/trekking/tests/test_views.py
  geotrek/trekking/views.py
  geotrek/zoning/tests/factories.py
  geotrek/zoning/tests/test_parsers.py
Labels: ✅ Tests, 👷 CI

#4349 ✨ [FEAT] Add schema_randonnee parser (refs #4022)
  docs/changelog.rst
  geotrek/locale/de/LC_MESSAGES/django.po
  geotrek/locale/en/LC_MESSAGES/django.po
  geotrek/locale/es/LC_MESSAGES/django.po
  geotrek/locale/fr/LC_MESSAGES/django.po
  geotrek/locale/it/LC_MESSAGES/django.po
  geotrek/locale/nl/LC_MESSAGES/django.po
  geotrek/trekking/locale/de/LC_MESSAGES/django.po
  geotrek/trekking/locale/en/LC_MESSAGES/django.po
  geotrek/trekking/locale/es/LC_MESSAGES/django.po
  geotrek/trekking/locale/fr/LC_MESSAGES/django.po
  geotrek/trekking/locale/it/LC_MESSAGES/django.po
  geotrek/trekking/locale/nl/LC_MESSAGES/django.po
  geotrek/trekking/parsers.py
  geotrek/trekking/tests/data/schema_randonnee_parser/add_medias_info_after_update.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/add_medias_info_before_update.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/correct_trek.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/del_medias_info_after_update.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/del_medias_info_before_update.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/incorrect_geoms.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/incorrect_parking_location.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/license_not_created.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/mod_medias_info_after_update.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/mod_medias_info_before_update.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/mod_medias_url_after_update.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/mod_medias_url_before_update.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/no_geom.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/no_parking_location.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/no_url.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/no_uuid.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/related_treks.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/related_treks_parent_does_not_exist.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/with_medias.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/with_null_medias.geojson
  geotrek/trekking/tests/test_parsers.py
Labels: ✨ Feature

#4366 :bug: [Bug] Fix missing Dockerfile path on make build scripts (fix #4365)
  Makefile
  docs/changelog.rst
Labels: 🐛 bug

#4363 📝 [DOC] Update release and maintenance doc
  docs/changelog.rst
  docs/contribute/contributing.rst
  docs/install/maintenance.rst
Labels: 📝 Documentation

#4376 bump appy to 1.0.18
  requirements.txt
Labels: dependencies, python

#4377 📝 [Documentation] Add note about certbot ssl configuration in nginx
  docs/changelog.rst
  docs/install/configuration.rst
Labels: 📝 Documentation

#4369 🐛 [BUG] Fix SchemaRandonneeParser url update (refs #4022)
  docs/changelog.rst
  geotrek/trekking/parsers.py
  geotrek/trekking/tests/data/schema_randonnee_parser/description_and_url.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/description_no_url.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/find_url_in_description.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/no_description_no_url.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/update_url_after.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/update_url_before.geojson
  geotrek/trekking/tests/data/schema_randonnee_parser/url_no_description.geojson
  geotrek/trekking/tests/test_parsers.py
Labels: 🐛 bug

#4380 Disable bionic tests
  .github/workflows/test.yml
Labels: 👷 CI

#4381 Improve docker image with labels and manifests
  .github/workflows/test.yml
  docker/Dockerfile
Labels: 💫 Improvements

#3509 👷 Publish docker image to Github docker registry as mirror
  .github/workflows/test.yml
  docs/changelog.rst
Labels: 👷 CI

#3282 Sync mobile and import views improvements
  docs/changelog.rst
  geotrek/api/templates/mobile/sync_mobile.html
  geotrek/common/static/common/css/import.css
  geotrek/common/static/common/css/sync.css
  geotrek/common/static/common/js/import.js
  geotrek/common/templates/common/import_dataset.html
  geotrek/common/templates/common/sync_rando.html
  geotrek/common/tests/test_views.py
  geotrek/common/views.py
Labels: to do
