Repository GeotrekCE/Geotrek-admin, pull requests merged in 2025-05, with the labels that each got.

#4669 Improve overpass queries for OpenStreetMap parsers
  docs/changelog.rst
  docs/import-data/import-touristic-data-systems.rst
  geotrek/common/parsers.py
  geotrek/common/tests/test_parsers.py
  geotrek/tourism/tests/test_parsers.py
  geotrek/trekking/tests/test_parsers.py
Labels: 💫 Improvements, python

#4690 [📝 Documentation] Add missing parameters from base.py
  docs/advanced-configuration/modules-and-components.rst
  docs/advanced-configuration/settings-for-geotrek-mobile.rst
  docs/changelog.rst
Labels: 📝 Documentation

#4678 Make eid for OpenStreetMap object as type+id
  docs/changelog.rst
  geotrek/common/parsers.py
  geotrek/tourism/parsers.py
  geotrek/tourism/tests/test_parsers.py
  geotrek/trekking/parsers.py
  geotrek/trekking/tests/test_parsers.py
Labels: 🐛 bug

#4674 Provides OpenStreetMap translations in the parser
  docs/changelog.rst
  docs/import-data/import-touristic-data-systems.rst
  geotrek/common/parsers.py
  geotrek/common/tests/test_parsers.py
  geotrek/tourism/parsers.py
  geotrek/tourism/tests/data/information_desk_OSM.json
  geotrek/tourism/tests/test_parsers.py
Labels: 💫 Improvements

#4670 Add OpenStreetMap parser for District
  docs/changelog.rst
  docs/import-data/import-areas.rst
  docs/import-data/import-touristic-data-systems.rst
  geotrek/common/parsers.py
  geotrek/tourism/parsers.py
  geotrek/zoning/parsers.py
  geotrek/zoning/tests/data/district_OSM.json
  geotrek/zoning/tests/data/district_multipolygon.json
  geotrek/zoning/tests/data/district_polygon.json
  geotrek/zoning/tests/test_parsers.py
Labels: 💫 Improvements

#4702 fix Directionnelle typo in signage fixtures
  docs/changelog.rst
  geotrek/signage/fixtures/basic.json
Labels: 💫 Improvements

#4671 Ensure linear topologies don't fragment when modified despite marker shift (refs #4657)
  docs/changelog.rst
  geotrek/core/path_router.py
  geotrek/core/static/core/multipath.js
  geotrek/core/tests/test_views.py
  geotrek/core/views.py
Labels: 🐛 bug

#4688 Improve docker image and installation
  .github/workflows/test.yml
  docker/Dockerfile
  docker/install/.env.dist
  docker/install/docker-compose.yml
  docs/installation-and-configuration/installation.rst
  geotrek/locale/de/LC_MESSAGES/django.po
  geotrek/locale/en/LC_MESSAGES/django.po
  geotrek/locale/es/LC_MESSAGES/django.po
  geotrek/locale/fr/LC_MESSAGES/django.po
  geotrek/locale/it/LC_MESSAGES/django.po
  geotrek/locale/nl/LC_MESSAGES/django.po
  geotrek/settings/base.py
  requirements-dev.txt
  requirements.txt
  ruff.toml
  setup.py
Labels: 💫 Improvements
