Repository GeotrekCE/Geotrek-admin, pull requests merged in 2025-09, with the labels that each got.

#4860 Simplify release and back-to-dev processes
  Makefile
  docs/contribute/guidelines.rst
Labels: 🛠️ Tools

#4919 Add locate control on each map
  cypress/integration/nav_create_path.js
  cypress/integration/nav_reports_workflow.js
  docs/changelog.rst
  geotrek/core/templates/core/path_list.html
  geotrek/core/tests/test_views.py
  geotrek/sensitivity/templates/sensitivity/sensitivearea_list.html
  geotrek/zoning/templates/zoning/_bbox_fragment.html
  requirements.txt
Labels: ✨ Feature

#4942 Fix parser crash when a row fails with any error
  docs/changelog.rst
  geotrek/common/parsers.py
  geotrek/common/tests/data/two_organisms.json
  geotrek/common/tests/test_parsers.py
  geotrek/zoning/tests/test_parsers.py
Labels: 🐛 bug

#4943 fix map loading with restricted areas
  docs/changelog.rst
  geotrek/zoning/templates/zoning/_bbox_fragment.html
Labels: 🐛 bug

#4948 Automate release process
  .github/workflows/dependencies.yml
  .github/workflows/doc.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: 👷 CI

#4981 bump mapentity to 8.14.4 and datatables to v2
  geotrek/cirkwi/tests/test_parsers.py
  geotrek/core/templates/core/core_listactions_fragment.html
  geotrek/land/templates/land/land_preactions_fragment.html
  requirements.txt
Labels: 🐛 bug, dependencies, python, javascript
