Repository GeotrekCE/Geotrek-admin, pull requests merged in 2025-10, with the labels that each got.

#4987 Fix makefile's build_doc cache
  Makefile
  docs/changelog.rst
Labels: 🐛 bug

#4883 [📝 Doc] Add main section blocks
  docs/about/geotrek.rst
  docs/changelog.rst
  docs/conf.py
  docs/contribute/contributing.rst
  docs/contribute/documentation.rst
  docs/index.rst
  docs/others/troubleshooting.rst
  docs/requirements.in
  docs/requirements.txt
  docs/user-manual/overview.rst
Labels: 📝 Documentation

#5003 fix(docker): Handle gunicorn configuration override correctly
  docker/Dockerfile
  docs/changelog.rst
Labels: 🐛 bug

#4537 Update to Django 5.2 LTS
  .github/workflows/test.yml
  docker-compose.yml
  docs/changelog.rst
  docs/installation-and-configuration/upgrade.rst
  docs/requirements.txt
  geotrek/api/tests/test_mobile/test_sync_mobile.py
  geotrek/authent/hashers.py
  geotrek/core/tests/test_commands.py
  geotrek/core/tests/test_path_split.py
  geotrek/settings/base.py
  requirements-dev.txt
  requirements.txt
  setup.cfg
  setup.py
Labels: dependencies, python, 🏗️ Maintenance
