Repository GeotrekCE/Geotrek-admin, pull requests merged in 2025-03, with the labels that each got.

#4543 📝 Fix doc URL in changelog
  docs/changelog.rst
Labels: 📝 Documentation

#4546 💄 [UI/UX] Max-width for attached files thumbnails
  docs/changelog.rst
  geotrek/common/templates/common/attachment_accessibility_list.html
  geotrek/common/templates/common/hdviewpoint_detail_fragment.html
Labels: 💄 UI/UX

#4545 [📝 Documentation] Add create extension pgrouting for application restore
  docs/changelog.rst
  docs/installation-and-configuration/maintenance.rst
Labels: 📝 Documentation

#4561 Fix postgis scripts availability
  .github/workflows/test.yml
  debian/control
  docs/changelog.rst
  tools/install-dev.sh
  tools/install.sh
Labels: 🐛 bug

#4564 Add postgis package info in manual debian install documentation
  docs/installation-and-configuration/installation.rst
Labels: 📝 Documentation

#4577 Fix log book filters
  docs/changelog.rst
  requirements.txt
Labels: 🐛 bug

#4567 Prevent trying to generate thumbnails for non-images
  docs/changelog.rst
  geotrek/common/admin.py
  geotrek/common/admin/__init__.py
  geotrek/common/admin/inlines.py
  geotrek/common/migrations/0038_remove_accessibilityattachment_creation_date_and_more.py
  geotrek/common/models.py
  geotrek/common/utils/file_infos.py
  geotrek/signage/views.py
  geotrek/tourism/admin.py
  geotrek/tourism/migrations/0055_auto_20250312_1650.py
  geotrek/tourism/migrations/0056_alter_informationdesk_photo.py
  geotrek/tourism/models.py
  geotrek/tourism/parsers.py
  geotrek/tourism/tests/test_admin.py
  geotrek/tourism/tests/test_parsers.py
Labels: 🐛 bug
