Repository GeotrekCE/Geotrek-admin, pull requests merged in 2025-04, with the labels that each got.

#4606 💫 [IMPR] Add default_fields_values dictionnary in Parser class
  docs/changelog.rst
  docs/import-data/import-touristic-data-systems.rst
  geotrek/common/parsers.py
  geotrek/common/tests/data/recordSource2.xls
  geotrek/common/tests/test_parsers.py
Labels: 💫 Improvements, python

#4605 Add OpenStreetMap parser for Information Desks
  docs/changelog.rst
  docs/import-data/import-touristic-data-systems.rst
  geotrek/common/parsers.py
  geotrek/common/tests/data/recordSource.xls
  geotrek/common/tests/test_parsers.py
  geotrek/tourism/parsers.py
  geotrek/tourism/tests/data/information_desk_OSM.json
  geotrek/tourism/tests/test_parsers.py
Labels: 💫 Improvements, python

#4607 Use constraints in model definition
  geotrek/common/functions.py
  geotrek/core/migrations/0039_auto_20250402_1205.py
  geotrek/core/migrations/0040_path_core_path_geom_is_valid_and_more.py
  geotrek/core/models.py
  geotrek/core/templates/core/sql/post_40_paths.sql
  geotrek/zoning/migrations/0104_auto_20250402_1530.py
  geotrek/zoning/migrations/0105_city_zoning_city__geom_is_valid_and_more.py
  geotrek/zoning/models.py
  geotrek/zoning/templates/zoning/sql/post_10_topologies.sql
Labels: ♻️ Refactoring

#4608 Use UV
  .github/actions/python-cache-requirements/action.yml
  .github/workflows/dependencies.yml
  .github/workflows/doc.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  Makefile
  dev-requirements.txt
  docker/Dockerfile
  docs/contribute/development.rst
  docs/requirements.txt
  requirements-dev.in
  requirements-dev.txt
  requirements.txt
Labels: ♻️ Refactoring

#4636 Fix doc CI workflow
  .github/workflows/doc.yml
  .github/workflows/test.yml
Labels: 👷 CI

#4653 Fix migration for information desk with no associated file
  geotrek/tourism/migrations/0055_auto_20250312_1650.py
Labels: 🚑 Hotfix

#4634 :dizzy: [IMPR] Add OpenStreetMap parser for POI
  docs/changelog.rst
  docs/import-data/import-touristic-data-systems.rst
  geotrek/common/parsers.py
  geotrek/trekking/parsers.py
  geotrek/trekking/tests/data/osm_poi_parser/POI_OSM.json
  geotrek/trekking/tests/test_parsers.py
Labels: 💫 Improvements, python

#4654 [📝 Documentation] Update infos about map settings and tourism/outdoor intersection margin
  docs/advanced-configuration/map-settings.rst
  docs/advanced-configuration/modules-and-components.rst
  docs/changelog.rst
Labels: 📝 Documentation

#4687 Fix exception handling on thumbnail generation
  geotrek/api/v2/serializers.py
  geotrek/common/locale/de/LC_MESSAGES/django.po
  geotrek/common/locale/en/LC_MESSAGES/django.po
  geotrek/common/locale/es/LC_MESSAGES/django.po
  geotrek/common/locale/fr/LC_MESSAGES/django.po
  geotrek/common/locale/it/LC_MESSAGES/django.po
  geotrek/common/locale/nl/LC_MESSAGES/django.po
  geotrek/common/mixins/models.py
  geotrek/settings/env_dev.py
  geotrek/tourism/models.py
Labels: 🐛 bug

#4635 Prevent change on internal user
  geotrek/authent/admin.py
  geotrek/authent/tests/test_admin.py
  geotrek/common/signals.py
  requirements.txt
Labels: 💫 Improvements
