Repository GeotrekCE/Geotrek-admin, pull requests merged in 2025-06, with the labels that each got.

#4727 Add OpenStreetMap parser for Restricted Area
  docs/changelog.rst
  docs/import-data/import-touristic-data-systems.rst
  geotrek/zoning/parsers.py
  geotrek/zoning/tests/data/OSM_multipolygon.json
  geotrek/zoning/tests/data/OSM_polygon.json
  geotrek/zoning/tests/data/district_multipolygon.json
  geotrek/zoning/tests/data/district_polygon.json
  geotrek/zoning/tests/data/restrictedarea_OSM.json
  geotrek/zoning/tests/test_parsers.py
Labels: 💫 Improvements

#4754 Parsers: ability to specify model instance used to filter parsed objects by geometry intersection
  docker-compose.yml
  docker/Dockerfile
  docs/changelog.rst
  docs/import-data/import-touristic-data-systems.rst
  geotrek/api/tests/test_v2.py
  geotrek/common/parsers.py
  geotrek/common/tests/data/touristic_content.json
  geotrek/common/tests/test_parsers.py
  geotrek/common/tests/test_views.py
  geotrek/core/templates/core/sql/post_10_utilities.sql
  geotrek/core/templates/core/sql/pre_10_cleanup.sql
  geotrek/core/tests/test_sql.py
  geotrek/core/tests/test_topology.py
  geotrek/tourism/parsers.py
  geotrek/tourism/tests/test_parsers.py
  geotrek/trekking/parsers.py
  geotrek/trekking/tests/test_parsers.py
Labels: 💫 Improvements

#4741 Fix delete=True in GeotrekParser when filtering by bbox or portal
  docs/changelog.rst
  geotrek/common/parsers.py
Labels: 🐛 bug

#4707 Add OpenStreetMap parser for Infrastructure
  docs/changelog.rst
  docs/import-data/import-touristic-data-systems.rst
  geotrek/infrastructure/parsers.py
  geotrek/infrastructure/tests/data/Infrastructure_OSM.json
  geotrek/infrastructure/tests/test_parsers.py
Labels: 💫 Improvements

#4722 Add OpenStreetMap parser for Touristic Content
  docs/changelog.rst
  docs/import-data/import-touristic-data-systems.rst
  geotrek/infrastructure/locale/de/LC_MESSAGES/django.po
  geotrek/infrastructure/locale/en/LC_MESSAGES/django.po
  geotrek/infrastructure/locale/es/LC_MESSAGES/django.po
  geotrek/infrastructure/locale/fr/LC_MESSAGES/django.po
  geotrek/infrastructure/locale/it/LC_MESSAGES/django.po
  geotrek/infrastructure/locale/nl/LC_MESSAGES/django.po
  geotrek/tourism/locale/de/LC_MESSAGES/django.po
  geotrek/tourism/locale/en/LC_MESSAGES/django.po
  geotrek/tourism/locale/es/LC_MESSAGES/django.po
  geotrek/tourism/locale/fr/LC_MESSAGES/django.po
  geotrek/tourism/locale/it/LC_MESSAGES/django.po
  geotrek/tourism/locale/nl/LC_MESSAGES/django.po
  geotrek/tourism/parsers.py
  geotrek/tourism/tests/data/touristic_content_OSM.json
  geotrek/tourism/tests/test_parsers.py
  geotrek/trekking/locale/de/LC_MESSAGES/django.po
  geotrek/trekking/locale/en/LC_MESSAGES/django.po
  geotrek/trekking/locale/es/LC_MESSAGES/django.po
  geotrek/trekking/locale/fr/LC_MESSAGES/django.po
  geotrek/trekking/locale/it/LC_MESSAGES/django.po
  geotrek/trekking/locale/nl/LC_MESSAGES/django.po
Labels: 💫 Improvements

#4689 Change City model to use integer as primary key instead of code
  docs/changelog.rst
  geotrek/api/mobile/serializers/common.py
  geotrek/api/tests/test_mobile/test_api_mobile_settings.py
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/filters.py
  geotrek/api/v2/serializers.py
  geotrek/core/tests/test_views.py
  geotrek/tourism/tests/test_functional.py
  geotrek/zoning/migrations/0106_auto_20250428_1557.py
  geotrek/zoning/models.py
Labels: 💫 Improvements, python

#4793 Update documentation copyright
  docs/conf.py
Labels: 📝 Documentation

#4804 Add city codes along identifier in API v2
  docs/changelog.rst
  docs/requirements.txt
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/serializers.py
  geotrek/common/functions.py
  geotrek/tourism/models.py
  geotrek/tourism/tests/test_models.py
  geotrek/trekking/managers.py
  geotrek/trekking/models.py
  geotrek/trekking/tests/test_models.py
  geotrek/zoning/mixins.py
  geotrek/zoning/tests/test_mixins.py
Labels: 💫 Improvements
