Repository GeotrekCE/Geotrek-admin, pull requests merged in 2025-01, with the labels that each got.

#4422 💄 [UI/UX] Restructure trek detail UI (refs #2967)
  cypress/integration/nav_tabs.js
  docs/changelog.rst
  geotrek/authent/templates/authent/authent_propertiestab_fragment.html
  geotrek/cirkwi/locale/de/LC_MESSAGES/django.po
  geotrek/cirkwi/locale/en/LC_MESSAGES/django.po
  geotrek/cirkwi/locale/es/LC_MESSAGES/django.po
  geotrek/cirkwi/locale/fr/LC_MESSAGES/django.po
  geotrek/cirkwi/locale/it/LC_MESSAGES/django.po
  geotrek/cirkwi/locale/nl/LC_MESSAGES/django.po
  geotrek/common/forms.py
  geotrek/common/locale/de/LC_MESSAGES/django.po
  geotrek/common/locale/en/LC_MESSAGES/django.po
  geotrek/common/locale/es/LC_MESSAGES/django.po
  geotrek/common/locale/fr/LC_MESSAGES/django.po
  geotrek/common/locale/it/LC_MESSAGES/django.po
  geotrek/common/locale/nl/LC_MESSAGES/django.po
  geotrek/common/templates/common/hdviewpoint_detail.html
  geotrek/common/tests/test_attachments.py
  geotrek/common/views.py
  geotrek/core/templates/core/path_detail_attributes.html
  geotrek/core/templates/core/trail_detail.html
  geotrek/core/templates/core/trail_detail_attributes.html
  geotrek/diving/templates/diving/dive_detail_attributes.html
  geotrek/feedback/locale/de/LC_MESSAGES/django.po
  geotrek/feedback/locale/en/LC_MESSAGES/django.po
  geotrek/feedback/locale/es/LC_MESSAGES/django.po
  geotrek/feedback/locale/fr/LC_MESSAGES/django.po
  geotrek/feedback/locale/it/LC_MESSAGES/django.po
  geotrek/feedback/locale/nl/LC_MESSAGES/django.po
  geotrek/feedback/templates/feedback/report_detail.html
  geotrek/feedback/templates/feedback/report_detail_attributes.html
  geotrek/infrastructure/templates/infrastructure/infrastructure_detail_attributes.html
  geotrek/outdoor/templates/outdoor/course_detail_attributes.html
  geotrek/outdoor/templates/outdoor/site_detail_attributes.html
  geotrek/sensitivity/templates/sensitivity/sensitivearea_detail_attributes.html
  geotrek/tourism/templates/tourism/touristiccontent_detail_attributes.html
  geotrek/tourism/templates/tourism/touristicevent_detail_attributes.html
  geotrek/trekking/locale/de/LC_MESSAGES/django.po
  geotrek/trekking/locale/en/LC_MESSAGES/django.po
  geotrek/trekking/locale/es/LC_MESSAGES/django.po
  geotrek/trekking/locale/fr/LC_MESSAGES/django.po
  geotrek/trekking/locale/it/LC_MESSAGES/django.po
  geotrek/trekking/locale/nl/LC_MESSAGES/django.po
  geotrek/trekking/templates/trekking/poi_detail_attributes.html
  geotrek/trekking/templates/trekking/service_detail_attributes.html
  geotrek/trekking/templates/trekking/trek_detail.html
  geotrek/trekking/templates/trekking/trek_detail_attributes.html
  requirements.txt
Labels: 💄 UI/UX

#4449 🐛 [BUG] Prevent objects from being returned several times in APIv2 by filtering on ManyToMany (refs #4448)
  docs/changelog.rst
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/filters.py
Labels: 🐛 bug

#4440 🐛 [BUG] Fix missing languages for 'published' field on Touristic Content in APIv2 (#4439)
  docs/changelog.rst
  geotrek/api/v2/serializers.py
Labels: 🐛 bug

#4451 🐛 [BUG] Fix flaky tests (refs #4070)
  docs/changelog.rst
  docs/install/import.rst
  docs/install/installation.rst
  docs/install/upgrade.rst
  geotrek/common/templates/common/sql/pre_20_extensions.sql
  geotrek/core/templates/core/sql/post_50_paths_split.sql
  tools/triggers_cascade_visualizers.py
Labels: 🐛 bug

#4468 💫 [IMPR] Add data migration: generation of pgRouting network topology
  docs/changelog.rst
  geotrek/core/migrations/0038_auto_20250130_0912.py
Labels: 💫 Improvements

#4469 💫 [IMPR] Fix clickable labels in Admin
  docs/changelog.rst
  geotrek/common/locale/de/LC_MESSAGES/django.po
  geotrek/common/locale/en/LC_MESSAGES/django.po
  geotrek/common/locale/es/LC_MESSAGES/django.po
  geotrek/common/locale/fr/LC_MESSAGES/django.po
  geotrek/common/locale/it/LC_MESSAGES/django.po
  geotrek/common/locale/nl/LC_MESSAGES/django.po
  geotrek/core/admin.py
  geotrek/core/locale/de/LC_MESSAGES/django.po
  geotrek/core/locale/en/LC_MESSAGES/django.po
  geotrek/core/locale/es/LC_MESSAGES/django.po
  geotrek/core/locale/fr/LC_MESSAGES/django.po
  geotrek/core/locale/it/LC_MESSAGES/django.po
  geotrek/core/locale/nl/LC_MESSAGES/django.po
  geotrek/diving/locale/de/LC_MESSAGES/django.po
  geotrek/diving/locale/en/LC_MESSAGES/django.po
  geotrek/diving/locale/es/LC_MESSAGES/django.po
  geotrek/diving/locale/fr/LC_MESSAGES/django.po
  geotrek/diving/locale/it/LC_MESSAGES/django.po
  geotrek/diving/locale/nl/LC_MESSAGES/django.po
  geotrek/feedback/locale/de/LC_MESSAGES/django.po
  geotrek/feedback/locale/en/LC_MESSAGES/django.po
  geotrek/feedback/locale/es/LC_MESSAGES/django.po
  geotrek/feedback/locale/fr/LC_MESSAGES/django.po
  geotrek/feedback/locale/it/LC_MESSAGES/django.po
  geotrek/feedback/locale/nl/LC_MESSAGES/django.po
  geotrek/infrastructure/locale/de/LC_MESSAGES/django.po
  geotrek/infrastructure/locale/en/LC_MESSAGES/django.po
  geotrek/infrastructure/locale/es/LC_MESSAGES/django.po
  geotrek/infrastructure/locale/fr/LC_MESSAGES/django.po
  geotrek/infrastructure/locale/it/LC_MESSAGES/django.po
  geotrek/infrastructure/locale/nl/LC_MESSAGES/django.po
  geotrek/outdoor/locale/de/LC_MESSAGES/django.po
  geotrek/outdoor/locale/en/LC_MESSAGES/django.po
  geotrek/outdoor/locale/es/LC_MESSAGES/django.po
  geotrek/outdoor/locale/fr/LC_MESSAGES/django.po
  geotrek/outdoor/locale/it/LC_MESSAGES/django.po
  geotrek/outdoor/locale/nl/LC_MESSAGES/django.po
  geotrek/sensitivity/locale/de/LC_MESSAGES/django.po
  geotrek/sensitivity/locale/en/LC_MESSAGES/django.po
  geotrek/sensitivity/locale/es/LC_MESSAGES/django.po
  geotrek/sensitivity/locale/fr/LC_MESSAGES/django.po
  geotrek/sensitivity/locale/it/LC_MESSAGES/django.po
  geotrek/sensitivity/locale/nl/LC_MESSAGES/django.po
  geotrek/tourism/admin.py
  geotrek/tourism/locale/de/LC_MESSAGES/django.po
  geotrek/tourism/locale/en/LC_MESSAGES/django.po
  geotrek/tourism/locale/es/LC_MESSAGES/django.po
  geotrek/tourism/locale/fr/LC_MESSAGES/django.po
  geotrek/tourism/locale/it/LC_MESSAGES/django.po
  geotrek/tourism/locale/nl/LC_MESSAGES/django.po
  geotrek/trekking/admin.py
  geotrek/trekking/locale/de/LC_MESSAGES/django.po
  geotrek/trekking/locale/en/LC_MESSAGES/django.po
  geotrek/trekking/locale/es/LC_MESSAGES/django.po
  geotrek/trekking/locale/fr/LC_MESSAGES/django.po
  geotrek/trekking/locale/it/LC_MESSAGES/django.po
  geotrek/trekking/locale/nl/LC_MESSAGES/django.po
Labels: 💫 Improvements
