Repository GeotrekCE/Geotrek-admin, pull requests merged in 2025-07, with the labels that each got.

#4808 Fix mobile api setting name for touristic content categories
  docs/changelog.rst
  geotrek/api/locale/de/LC_MESSAGES/django.po
  geotrek/api/locale/en/LC_MESSAGES/django.po
  geotrek/api/locale/es/LC_MESSAGES/django.po
  geotrek/api/locale/fr/LC_MESSAGES/django.po
  geotrek/api/locale/it/LC_MESSAGES/django.po
  geotrek/api/locale/nl/LC_MESSAGES/django.po
  geotrek/api/mobile/views/common.py
  geotrek/infrastructure/locale/fr/LC_MESSAGES/django.po
  geotrek/tourism/locale/de/LC_MESSAGES/django.po
  geotrek/tourism/locale/en/LC_MESSAGES/django.po
  geotrek/tourism/locale/es/LC_MESSAGES/django.po
  geotrek/tourism/locale/fr/LC_MESSAGES/django.po
  geotrek/tourism/locale/it/LC_MESSAGES/django.po
  geotrek/tourism/locale/nl/LC_MESSAGES/django.po
  geotrek/zoning/locale/de/LC_MESSAGES/django.po
  geotrek/zoning/locale/en/LC_MESSAGES/django.po
  geotrek/zoning/locale/es/LC_MESSAGES/django.po
  geotrek/zoning/locale/fr/LC_MESSAGES/django.po
  geotrek/zoning/locale/it/LC_MESSAGES/django.po
  geotrek/zoning/locale/nl/LC_MESSAGES/django.po
Labels: 💫 Improvements

#4818 Deprecate facebook reference in portals
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/serializers.py
  geotrek/common/locale/de/LC_MESSAGES/django.po
  geotrek/common/locale/en/LC_MESSAGES/django.po
  geotrek/common/locale/es/LC_MESSAGES/django.po
  geotrek/common/locale/fr/LC_MESSAGES/django.po
  geotrek/common/locale/it/LC_MESSAGES/django.po
  geotrek/common/locale/nl/LC_MESSAGES/django.po
  geotrek/common/migrations/0018_auto_20210528_1232.py
  geotrek/common/migrations/0040_remove_targetportal_facebook_id_and_more.py
  geotrek/common/models.py
  geotrek/common/templates/common/sql/post_90_defaults.sql
  geotrek/common/tests/test_sql.py
  geotrek/locale/de/LC_MESSAGES/django.po
  geotrek/locale/en/LC_MESSAGES/django.po
  geotrek/locale/es/LC_MESSAGES/django.po
  geotrek/locale/fr/LC_MESSAGES/django.po
  geotrek/locale/it/LC_MESSAGES/django.po
  geotrek/locale/nl/LC_MESSAGES/django.po
  geotrek/outdoor/tests/data/geotrek_parser_v2/portal.json
  geotrek/settings/base.py
Labels: ♻️ Refactoring

#4837 Update readme
  README.md
  docs/changelog.rst
Labels: 📝 Documentation

#4829 Order touristic contents of treks by category in mobile API
  docs/changelog.rst
  geotrek/api/mobile/views/trekking.py
  geotrek/api/tests/test_mobile/test_sync_mobile.py
Labels: 💫 Improvements
