Repository GeotrekCE/Geotrek-admin, pull requests merged in 2025-02, with the labels that each got.

#4479 Fix path picture in intervention form (#4450)
  geotrek/maintenance/forms.py
  geotrek/maintenance/locale/de/LC_MESSAGES/django.po
  geotrek/maintenance/locale/en/LC_MESSAGES/django.po
  geotrek/maintenance/locale/es/LC_MESSAGES/django.po
  geotrek/maintenance/locale/fr/LC_MESSAGES/django.po
  geotrek/maintenance/locale/it/LC_MESSAGES/django.po
  geotrek/maintenance/locale/nl/LC_MESSAGES/django.po
Labels: 🐛 bug

#4481 Delete old useless jstests folder
  Makefile
  docs/contribute/contributing.rst
  geotrek/jstests/README.md
  geotrek/jstests/_nav-map-export.js
  geotrek/jstests/_nav-utils.js
  geotrek/jstests/export-path.js
  geotrek/jstests/export-trek.js
  geotrek/jstests/index.html
  geotrek/jstests/nav-history-tabs.js
  geotrek/jstests/nav-intervention-create.js
  geotrek/jstests/nav-path-edit.js
  geotrek/jstests/nav-poi-create.js
  geotrek/jstests/nav-tourism-touristiccontent-form.js
  geotrek/jstests/nav-tourism-touristiccontent-list.js
  geotrek/jstests/nav-trek-create.js
  geotrek/jstests/nav-trek-detail.js
  geotrek/jstests/package.json
  geotrek/jstests/test.core.js
Labels: 🏗️ Maintenance

#4467 🐛 [BUG] Fix gpx and kml parsing: geom is an empty GeometryCollection
  docs/changelog.rst
  geotrek/common/tests/test_utils.py
  geotrek/common/utils/parsers.py
  geotrek/trekking/tests/data/apidae_trek_parser/trace_with_only_two_duplicate_coordinates.kml
  geotrek/trekking/tests/data/apidae_trek_parser/trace_with_only_two_duplicate_track_points.gpx
Labels: 🐛 bug

#4483 Allow to customize develoment postgres docker image in .env file
  docker-compose.yml
Labels: 🛠️ Tools

#4484 [DOC] Update documentation theme and content. Re-organize sections.
  docs/_static/extra_css.css
  docs/about/geotrek.rst
  docs/advanced-configuration/application-settings.rst
  docs/advanced-configuration/attachments.rst
  docs/advanced-configuration/edition.rst
  docs/advanced-configuration/feedback-report-settings.rst
  docs/advanced-configuration/interface.rst
  docs/advanced-configuration/map-settings.rst
  docs/advanced-configuration/modules-and-components.rst
  docs/advanced-configuration/settings-for-geotrek-mobile.rst
  docs/conf.py
  docs/contribute/contributing.rst
  docs/contribute/design.rst
  docs/contribute/development.rst
  docs/contribute/documentation.rst
  docs/contribute/guidelines.rst
  docs/contribute/translating.rst
  docs/images/advanced-configuration/status.jpg
  docs/images/advanced-configuration/zoning-combo-boxes.png
  docs/images/installation-and-configuration/toolextent.jpg
  docs/images/tutorials/qgis/Connexion_bdd.png
  docs/images/tutorials/qgis/groupe_couches.png
  docs/images/tutorials/topologies-1.jpeg
  docs/images/tutorials/topologies-2.jpeg
  docs/images/tutorials/topologies-3.jpeg
  docs/images/tutorials/update-basemaps.jpeg
  docs/images/user-manual/geotrek-login.png
  docs/import-data/import-aggregator.rst
  docs/import-data/import-areas.rst
  docs/import-data/import-dem-raster.rst
  docs/import-data/import-other-data.rst
  docs/import-data/import-paths.rst
  docs/import-data/import-touristic-data-systems.rst
  docs/import-data/minimal-initial-data.rst
  docs/index.rst
  docs/install/advanced-configuration.rst
  docs/install/import.rst
  docs/install/loading-data.rst
  docs/install/synchronization.rst
  docs/installation-and-configuration/configuration.rst
  docs/installation-and-configuration/exploitation-commands.rst
  docs/installation-and-configuration/installation.rst
  docs/installation-and-configuration/maintenance.rst
  docs/installation-and-configuration/synchronization.rst
  docs/installation-and-configuration/upgrade.rst
  docs/others/authors.rst
  docs/others/troubleshooting.rst
  docs/tutorials/topologies-issues.rst
  docs/tutorials/update-basemaps-layers.rst
  docs/tutorials/vizualize-data-in-qgis.rst
  docs/usage/touristic-modules.rst
  docs/user-manual/apis.rst
  docs/user-manual/configuration-ttw.rst
  docs/user-manual/editing-objects.rst
  docs/user-manual/interfaces.rst
  docs/user-manual/management-modules.rst
  docs/user-manual/overview.rst
  docs/user-manual/static-pages.rst
  docs/user-manual/touristic-modules.rst
Labels: 📝 Documentation

#4486 [DOC] Add new info about adding languages
  docs/changelog.rst
  docs/installation-and-configuration/configuration.rst
Labels: 📝 Documentation

#4488 Support Ubuntu jammy 22.04
  .github/workflows/test.yml
  debian/control
  debian/geotrek-admin.config
  docs/advanced-configuration/modules-and-components.rst
  docs/changelog.rst
  docs/installation-and-configuration/installation.rst
  docs/installation-and-configuration/upgrade.rst
  tools/install-dev.sh
  tools/install.sh
Labels: 💫 Improvements

#4490 💫 [IMPR] Add sensitive areas to mobile API and sync
  docs/changelog.rst
  geotrek/api/locale/de/LC_MESSAGES/django.po
  geotrek/api/locale/en/LC_MESSAGES/django.po
  geotrek/api/locale/es/LC_MESSAGES/django.po
  geotrek/api/locale/fr/LC_MESSAGES/django.po
  geotrek/api/locale/it/LC_MESSAGES/django.po
  geotrek/api/locale/nl/LC_MESSAGES/django.po
  geotrek/api/management/commands/sync_mobile.py
  geotrek/api/mobile/serializers/common.py
  geotrek/api/mobile/serializers/sensitivity.py
  geotrek/api/mobile/views/common.py
  geotrek/api/mobile/views/trekking.py
  geotrek/api/tests/test_mobile/test_api_mobile.py
  geotrek/api/tests/test_mobile/test_api_mobile_settings.py
  geotrek/api/tests/test_mobile/test_sync_mobile.py
  geotrek/core/locale/fr/LC_MESSAGES/django.po
  geotrek/maintenance/locale/fr/LC_MESSAGES/django.po
Labels: 💫 Improvements

#4493 fix uml database schemas and autodoc usage
  Makefile
  docker/Dockerfile
  docs/data-model/authent.pdf
  docs/data-model/cirkwi.pdf
  docs/data-model/core.pdf
  docs/data-model/diving.pdf
  docs/data-model/feedback.pdf
  docs/data-model/flatpages.pdf
  docs/data-model/global.pdf
  docs/data-model/infrastructure.pdf
  docs/data-model/land.pdf
  docs/data-model/maintenance.pdf
  docs/data-model/outdoor.pdf
  docs/data-model/sensitivity.pdf
  docs/data-model/signage.pdf
  docs/data-model/tourism.pdf
  docs/data-model/trekking.pdf
  docs/data-model/zoning.pdf
Labels: 📝 Documentation

#4496 bump mapentity to 8.11.1
  requirements.txt
Labels: dependencies, python

#4511 Bump all django-large-images dependencies
  requirements.txt
Labels: dependencies, python

#4533 Improve makefile
  .gitignore
  Makefile
  docker-compose.yml
  docker/Dockerfile
  docs/contribute/documentation.rst
Labels: 🛠️ Tools

#4534 Add code filter in signage list
  docs/changelog.rst
  geotrek/signage/filters.py
Labels: 💫 Improvements

#4489 Fix typing error in touristic module documentation
  docs/changelog.rst
  docs/user-manual/configuration-ttw.rst
  docs/user-manual/editing-objects.rst
  docs/user-manual/touristic-modules.rst
Labels: 📝 Documentation

#4535 Bump mapentity and allow WebP attachment pictures
  geotrek/settings/base.py
  requirements.txt
Labels: dependencies, python

#4536 Delete deprecated code in django 5.2
  Makefile
  geotrek/api/tests/test_v2.py
  geotrek/api/v2/serializers.py
  geotrek/api/v2/views/flatpages.py
  geotrek/common/utils/__init__.py
  geotrek/core/tests/test_topology.py
  geotrek/flatpages/models.py
  geotrek/infrastructure/filters.py
  geotrek/infrastructure/models.py
  geotrek/infrastructure/tests/factories.py
  geotrek/infrastructure/tests/test_views.py
  geotrek/maintenance/models.py
  geotrek/signage/tests/test_admin.py
  geotrek/tourism/filters.py
  geotrek/tourism/models.py
  requirements.txt
  setup.py
Labels: 💫 Improvements

#4544 [📝 Documentation] Update docker command for sensitivity fixtures
  docs/advanced-configuration/modules-and-components.rst
  docs/changelog.rst
Labels: 📝 Documentation
